-- ============================================================
-- CATALOGO DE MEDICAMENTOS
-- Fuente: CATALOGO DE MEDICAMENTOS - LIMPIO.xlsx
-- Total: 593 items (filtrada 1 entrada basura del archivo origen)
-- Idempotente: TRUNCATE + INSERT.
-- ============================================================

CREATE TABLE IF NOT EXISTS catalogo_medicamentos (
  id     SERIAL PRIMARY KEY,
  nombre TEXT UNIQUE NOT NULL,
  activo BOOLEAN DEFAULT TRUE,
  creado_en TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_catalogo_medicamentos_nombre ON catalogo_medicamentos (nombre);

ALTER TABLE catalogo_medicamentos ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS lectura_autenticados_catalogo_med ON catalogo_medicamentos;
CREATE POLICY lectura_autenticados_catalogo_med ON catalogo_medicamentos
  FOR SELECT TO authenticated USING (true);

TRUNCATE catalogo_medicamentos RESTART IDENTITY;

INSERT INTO catalogo_medicamentos (nombre) VALUES
  ('Acalabrutinib Capsulas 100mg.'),
  ('Aciclovir Comprimidos 200 mg'),
  ('Aciclovir Solucion inyectable 250 mg'),
  ('Aciclovir Tabletas 400 mg'),
  ('Aciclovir Ungüento oftalmico 3 g/ 100 g Envase con 4.5 g.'),
  ('Aciclovir Ungüento oftalmico 3 g/ 100 g Envase con 4.5 g. GENERICO'),
  ('Acido Tranexamico 100mg/ml, solucion inyectable. Ampula de 10ml.'),
  ('Acido Tranexamico 100mg/ml, solucion inyectable. Ampula de 5ml.'),
  ('Acido Ursodeoxicolico Capsulas 250 mg'),
  ('Acido acetilsalicilico Tabletas 500 mg'),
  ('Acido acetilsalicilico Tabletas 500 mg ANTACSAL'),
  ('Acido alendronico (alendronato) 10 mg. Tabletas o caps.'),
  ('Acido alendronico 10 mg, tabletas o comprimidos  PISA-FOSALACIN'),
  ('Acido folico Tabletas 0.4 mg U00-03-01-2023-031741-ASF'),
  ('Acido folinico Solucion inyectable 50 mg ampolleta con 4 ml'),
  ('Acido folinico Tabletas 15 mg'),
  ('Acido micofenolico (micofenolato mofetilo). Comprimido 500 mg'),
  ('Acido retinoico Crema 500 µg/ g Envase con 20 g'),
  ('Acido retinoico Crema 500 µg/ g Envase con 20 g IMSS'),
  ('Acido zoledronico solucion inyectable 4mg/5ml'),
  ('Acido zoledronico solucion inyectable 4mg/5ml PRISHA'),
  ('Adenocina Sol. Iny. 6mg/2ml Frasco ampula c/2ml PISA-PISDENO'),
  ('Agua inyectable Solucion inyectable 10 ml'),
  ('Agua inyectable Solucion inyectable 500 ml'),
  ('Albendazol Suspension oral 20 mg/ml Envase con 20 ml'),
  ('Albendazol Tabletas 200 mg'),
  ('Alfa cetoanalogos de aminoacidos Grageas 630 mg'),
  ('Alfadornasa Solucion inyectable 2.5 mg. Ampolleta con 2.5 ml'),
  ('Alibour Polvo Cobre 177 mg/g ,zinc 619.5 mg/g alcanfor 26.5 mg/g 12 sobres con 2.2 g'),
  ('Alibour Polvo Cobre 177 mg/g ,zinc 619.5 mg/g alcanfor 26.5 mg/g 12 sobres con 2.2 g ALOSUAN'),
  ('Alibour Polvo Cobre 177 mg/g ,zinc 619.5 mg/g alcanfor 26.5 mg/g 12 sobres con 2.2 g SUANCA'),
  ('Alopurinol Tabletas 300 mg BIORESEARCH'),
  ('Alprazolam 0.5 mg'),
  ('Alprazolam Tabletas 0.25 mg'),
  ('Alprazolam Tabletas 0.25 mg PISA-PISALDRA'),
  ('Alprostadil solucion inyectable de 500 mcg/ml, ampolletas'),
  ('Alteplasa (activador tisular de plasminogeno humano) 50 mg sol. iny.'),
  ('Aluminio y magnesio Suspension oral Al 185 mg, Mg 200 o 447.3 mg Envase con 240 ml'),
  ('Aluminio y magnesio Tabletas masticables Al 200 mg, Mg 200 o 447.3 mg'),
  ('Aluminio y magnesio Tabletas masticables Al 200 mg, Mg 200 o 447.3 mg IMSS'),
  ('Ambroxol Comprimidos 30 mg'),
  ('Ambroxol Solucion oral 300 mg/ 100 ml Envase con 120 ml'),
  ('Amfotericina B Solucion inyectable 50 mg'),
  ('Amikacina 500mg. Solucion intyectable. Envase c/2 ampolletas.'),
  ('Amikacina Solucion inyectable 100 mg/ 2 ml'),
  ('Amikacina Solucion inyectable 500 mg/ 2 ml'),
  ('Aminoacidos cristalinos Solucion inyectable al 10% Pediatricos Envase con 500 ml'),
  ('Aminofilina Solucion inyectable 250 mg/ 10 ml ampolletas con 5 ml'),
  ('Aminofilina Solucion inyectable 250 mg/ 10 ml ampolletas con 5 ml PISA-AMOFILIN'),
  ('Amiodarona Solucion inyectable 150 mg ampolletas con 3 ml'),
  ('Amiodarona Tabletas 200 mg'),
  ('Amitriptilina Tabletas 25 mg'),
  ('Amlodipino 5mg. Tableta o capsula.'),
  ('Amoxicilina 500mg / acido clavulanico 125mg tabletas'),
  ('Amoxicilina 875mg / acido clavulanico 125mg tabletas'),
  ('Amoxicilina Capsulas 500 mg'),
  ('Amoxicilina Suspension oral 500 mg/ 5 ml Envase con 75 ml'),
  ('Ampicilina Suspension oral 250 mg/ 5 ml Envase con 60 ml'),
  ('Ampicilina Suspension oral 250 mg/ 5 ml Envase con 60 ml GENÉRICO'),
  ('Ampicilina Tabletas o capsulas 500 mg GENÉRICO'),
  ('Aprepitant, 1 capsula 125mg, 2 capsulas de 80mg'),
  ('Aripiprazol tabletas de 15 mg'),
  ('Atorvastatina 20mg. Tabletas'),
  ('Atorvastatina tabletas 20 mg PSICOFARMA'),
  ('Atosiban, solucion inyectable 37.5mg/5ml, envase c/5 ml'),
  ('Atosiban, solucion inyectable, 6.75mg/0.9ml, envase c/0.9ml'),
  ('Atropina Solucion inyectable 1 mg/ml'),
  ('Azacitidina 100mg solucion inyectable'),
  ('Azatioprina Tabletas 50 mg RAAM'),
  ('Azitromicina suspencion 200mg/5ml, polvo para reconstituir 10ml'),
  ('Azitromicina tabletas de 500 mg'),
  ('Beclometasona dipropionato de Aerosol 0.0587 g/ 100 g Inhalador con 200 dosis de 50 µg'),
  ('Beclometasona dipropionato de Suspension aerosol 0.294 g/100 g Inhalador con 200 dosis de 250 µg'),
  ('Beclometasona/Formoterol 1.724mg/0.103mg, aerosol. Envase c/120 dosis'),
  ('Beclometazona 100µg / Formoterol 6µg / Glicopirronio 12.5µg, frasco c/120 dosis e inhalador'),
  ('Bencilpenicilina procainica c/bencilpenicilina cristalina S.I. 300,000UI/100,000UI (diluyente c/2ml)'),
  ('Bencilpenicilina procainica c/bencilpenicilina cristalina S.I. 600 000UI/200 000UI (diluyente c/2ml)'),
  ('Bendamustina 100mg, ámpula.'),
  ('Benralizumab jeringa prellenada con dosis única de 30mg/ml FASENRA'),
  ('Benzatina bencilpenicilina Suspension inyectable 1 200 000 UI (diluyente c/5ml) U00-03-01-2023-031200-ASF'),
  ('Benzoilo Locion dermica o gel dermico 5 g/100 ml Envase con 30 ml'),
  ('Besilato de cisatracurio 2mg/ml Solucion inyectable. Envase c/5ml'),
  ('Betametasona (dipropionato de) Ungüento 50 mg/100g Envase c/30g'),
  ('Betametasona Solucion inyectable 4 mg/ ml frasco ampula'),
  ('Bevacizumab 100 mg Solución Inyectable. Frasco ámpula con 4 ml.'),
  ('Bezafibrato Tabletas 200 mg'),
  ('Bicalutamida Tabletas 50 mg'),
  ('Bicarbonato de sodio  Solucion inyectable al 7.5% 0.75 g/10 ml. Envase c/10 ml'),
  ('Bicarbonato de sodio Solucion inyectable al 7.5% 3.75 g/50 ml envase c/50 ml'),
  ('Bictegravir 52.5mg / Emtricitabina 200mg / Tenofovir Alafenamida 28mg'),
  ('Biperideno Tabletas 2 mg'),
  ('Bismuto subsalicilato de Suspension oral 1.750g/100ml Envase con 240ml'),
  ('Bisoprolol tabletas 2.5mg'),
  ('Bleomicina Solucion inyectable 15 UI frasco ampula y diluyente c/5 ml'),
  ('Blinatumomab solucion inyectable fco amp con liofilizado con 35mcg'),
  ('Bortezomib Solucion Inyectable 3.5mg. Liofilizado.'),
  ('Bosentan tabletas de 62.5 mg'),
  ('Brentuximab vedotin 50mg S.I.'),
  ('Bromuro de Tiotropio, capsula 18 µg (repuesto)'),
  ('Budesonida (micronizada) 0.250 mg, suspension en aerosol, envase c/2ml en sobre de aluminio PULMICORT'),
  ('Budesonida (micronizada) polvo, envase c/200 dosis y dispositivo inhalador'),
  ('Budesonida aerosol p/inhalación bucal, 4.285mg/g env c/200 dosis de 200µg c/u + disp inhalador'),
  ('Bumetanida Tabletas o Capsulas 10mg.'),
  ('Bupivacaina Solucion inyectable 150 mg/30ml (5mg/ml). Envase c/30ml U00-03-02-2023-031714-ASF'),
  ('Bupivacaina hiperbarica Solucion inyectable Bupivacaina 15 mg/ml Dextrosa 240 mg. ampolletas c/3ml PISA-BUVACAINA PESADA'),
  ('Buprenorfina Solucion inyectable 0.30mg/ml. frasco ampula c/1ml'),
  ('Buprenorfina Solucion inyectable 0.30mg/ml. frasco ampula c/1ml PSICOFARMA'),
  ('Buprenorfina parche 20 mg'),
  ('Buprenorfina parche 30 mg'),
  ('Buprenorfina parche 5mg.'),
  ('Butilhioscina Grageas 10mg'),
  ('Butilhioscina Solucion inyectable 20mg/ ml. Ampolletas c/1ml'),
  ('Butilhioscina Solucion inyectable 20mg/ ml. Ampolletas c/1ml ALPHARMA'),
  ('Butilhioscina/metamizol Grageas 10 mg/250mg'),
  ('Calcitriol (1 alfa 25 dihidroxicolicolecalciferol) Capsulas de gelatina blanda 0.25µg'),
  ('Carbamazepina Susp. oral 100 mg/5ml. Envase c/120 ml y vaso dosificador de 5ml, adosado al envase'),
  ('Carbamazepina Tabletas 200 mg'),
  ('Carbetocina, solucion inyectable 100µg'),
  ('Carbon activado Polvo REVITOX'),
  ('Carbonato de calcio 600mg/Vitamina D3 62.mg. Tabletas.'),
  ('Carboplatino Solucion Inyectable 450mg. Liofilizado'),
  ('Carboplatino Solucion inyectable 150 mg'),
  ('Caseinato de calcio Polvo Proteinas 90g, lipidos 2g Envase c/100g.'),
  ('Caspofungina 50 mg, Solución Inyectable. Envase con polvo para10.5 ml (7mg/ml)'),
  ('Caspofungina 50 mg, Solución Inyectable. Envase con polvo para10.5 ml (7mg/ml) FUZITRAN'),
  ('Cefalexina Capsulas o tabletas 500 mg'),
  ('Cefalotina Solucion inyectable 1g/5ml (diluyente c/5ml)'),
  ('Cefepima Solucion inyectable 1g (diluyente c/10ml)'),
  ('Cefixima 100mg/5ml. Suspension oral. Frasco con polvo para reconstituir 50ml.'),
  ('Cefotaxima Solucion inyectable 1g/4ml (diluyente c/4ml)'),
  ('Ceftazidima Solucion inyectable 1g (diluyente c/3ml)'),
  ('Ceftazidima-Avibactam 200mg/500mg. Solucion para perfusion. Frascos viales con polvo.'),
  ('Ceftriaxona Solucion inyectable 1g/10ml (diluyente c/10ml)'),
  ('Ceftriaxona Solucion inyectable 1g/10ml (diluyente c/10ml) AUROVIAX'),
  ('Celecoxib Capsulas 100mg TIAGOROL'),
  ('Celecoxib Capsulas 200mg'),
  ('Ciclofosfamida Solucion inyectable 200 mg'),
  ('Ciclofosfamida Solucion inyectable 500 mg'),
  ('Ciclofosfamida solucion inyectable 1 gr'),
  ('Ciclosporina A Solucion o Emulsion oral 100 mg/ml frasco 50 ml y pipeta dosificadora'),
  ('Cinitaprida (Bitartrato) Comprimido 1 mg'),
  ('Cinitaprida granulado 1mg, sobre'),
  ('Ciprofloxacino Solucion inyectable 200mg/100ml. Frasco ampula c/100ml'),
  ('Ciprofloxacino Tabletas o capsulas 250 mg'),
  ('Ciprofloxacino suspension 250mg/5ml, envase c/5g y 93ml de diluyente'),
  ('Cisaprida Suspension oral 1mg/ml Envase c/60ml'),
  ('Cisplatino solucion inyectable 10mg. Frasco ampula c/10ml'),
  ('Citarabina Solucion inyectable 500 mg/ 10 ml frasco ampula c/10ml'),
  ('Citrato de cafeina 20mg. Solucion Inyectable. Envase c/10 frascos amp. de 1ml.'),
  ('Citrato de cafeina 20mg/ml,  ampulas de 1ml'),
  ('Claritromicina Tabletas 250 mg'),
  ('Claritromicina Tabletas 500 mg'),
  ('Clindamicina Capsulas 300 mg'),
  ('Clindamicina Solucion inyectable 300mg/2ml ampolleta c/2ml'),
  ('Clioquinol (Yodoclorohidroxiquinoleina) Crema 30 mg/g Envase con 20 g ALPHARMA'),
  ('Clonazepam Solucion oral 2.5 mg/ ml Envase con 10 ml y gotero integral'),
  ('Clonazepam Solucion oral 2.5 mg/ ml Envase con 10 ml y gotero integral PSICOFARMA'),
  ('Clonazepam Solucion oral 2.5 mg/ ml Envase con 10 ml y gotero integral RIMASTINE'),
  ('Clonazepam Tabletas 2 mg'),
  ('Clonazepam Tabletas 2 mg PSICOFARMA'),
  ('Clopidogrel Grageas 75 mg'),
  ('Clorambucilo Tabletas 2 mg'),
  ('Cloranfenicol Solucion oftalmica 5 mg/ml Envase con gotero integral con 15 ml'),
  ('Cloranfenicol Solucion oftalmica 5 mg/ml Envase con gotero integral con 15 ml CLORAMFENI OFTENO'),
  ('Clorfenamina (Clorfeniramina) Jarabe 0.5 mg/ ml Envase con 60 ml'),
  ('Clorfenamina (Clorfeniramina) Tabletas 4 mg'),
  ('Clorhidrato de Dexrazoxano, solución inyectable, 500 mg'),
  ('Clorhidrato de Dexrazoxano, solución inyectable, 500 mg DEXPEXEL'),
  ('Clorhidrato de Dexrazoxano, solución inyectable, 500 mg DONECOL'),
  ('Cloropiramina Solucion inyectable 20mg/2ml Ampolletas c/2ml'),
  ('Cloroquina Tabletas 150 mg GENÉRICO'),
  ('Clortalidona Tabletas 50 mg'),
  ('Cloruro de potasio Solucion inyectable 1.49g/10ml. ampolletas c/10ml'),
  ('Cloruro de sodio 50 mg. Pomada o Solución oftalmica. Env 7gr ó Gotero 10ml'),
  ('Cloruro de sodio Solucion inyectable al 0.9% 1000 ml'),
  ('Cloruro de sodio Solucion inyectable al 0.9% 250 ml'),
  ('Cloruro de sodio Solucion inyectable al 17.7% ampolletas con 10 ml'),
  ('Cloruro de sodio al 9% y Glucosa al 5%, solucion inyectable, envase c/1000 ml'),
  ('Cloruro de sodio al 9% y Glucosa al 5%, solucion inyectable, envase c/500 ml'),
  ('Clozapina Comprimidos 100 mg'),
  ('Clozapina Comprimidos 100 mg PSICOFARMA'),
  ('Colchicina Tabletas 1 mg'),
  ('Colistemitato de sodio solucion inyectable 150mg/2ml'),
  ('Complejo B Tabletas o capsulas Tiamina 100 mg, piridoxina 5 mg, cianocobalamina 50 µg BIOTRIVIN'),
  ('Complejo coagulante anti-inibidor del factor VIII Sol. Iny. 1000 UFEIBA. Proteina Humana  400-1200mg'),
  ('Complejo coagulante anti-inibidor del factor VIII Sol. Iny. 500 UFEIBA. Proteina P Humana  200-600mg'),
  ('Dacarbazina Solucion inyectable 200 mg'),
  ('Dactinomicina (actinomicina D) Solucion inyectable 0.5mg'),
  ('Dactinomicina (actinomicina D) Solucion inyectable 0.5mg COSMEGEN'),
  ('Danazol Capsulas o comprimidos 100 mg'),
  ('Dapagliflozina propanodiol equivalente a 10 mg de dapagliflozina'),
  ('Dasatinib tabletas 50 mg'),
  ('Daunorubicina Solucion inyectable 20 mg'),
  ('Daunorubicina Solucion inyectable 20 mg GENÉRICO'),
  ('Deferasirox comprimidos 500mg'),
  ('Denosumab 60mg, jeringa prellenada con 1ml.'),
  ('Desfluorano liquido envase c/240 ml'),
  ('Desmopresina Solucion nasal 89 µg/ ml Envase nebulizador c/2.5 ml.'),
  ('Desmopresina solucion inyectable 15µg/ml,'),
  ('Dexametasona Tabletas 0.5 mg'),
  ('Dexametasona solucion inyectable 8 mg/2ml ampolleta c/2ml'),
  ('Dexmedetomidina 200µg solucion inyectable. Envase c/5 frascos ampula'),
  ('Diazepam Solucion inyectable 10 mg/2 ml ampolletas c/2ml'),
  ('Diazepam Tabletas 10 mg'),
  ('Diazepam solucion inyectable 10mg/2ml ampolletas c/2ml'),
  ('Diclofenaco Capsula o gragea de liberacion prolongada 100 mg'),
  ('Diclofenaco Solucion inyectable 75mg/3ml ampolletas c/3ml'),
  ('Diclofenaco Solucion oftalmica 1 mg/ml Envase con gotero integral con 15 ml'),
  ('Dicloxacilina Capsulas o comprimidos 500 mg'),
  ('Dicloxacilina Suspension oral 250 mg/ 5 ml Envase con 60 ml'),
  ('Dieta elemental. Polvo Proteinas, lipidos, carbohidratos. Pqte c/6 sobres de 80.4g c/u'),
  ('Dieta polimerica a base de caseinato de calcio Polvo Env c/400 a 454g con o sin sabor'),
  ('Dieta polimerica s/fibra Susp. oral Prot, lip, carb Envase con 236 o 250 ml'),
  ('Difenhidramina Jarabe 12.5 mg/ 5 ml Envase con 60 ml'),
  ('Difenhidramina Solucion inyectable 100mg/10ml frasco ampula c/10ml.'),
  ('Difenhidramina Solucion inyectable 100mg/10ml frasco ampula c/10ml. FARMADEXTRUM'),
  ('Difenidol Solucion inyectable 40mg/2ml ampolletas c/2ml'),
  ('Difenidol Tabletas 25 mg'),
  ('Digoxina Elixir 0.05 mg/ml Envase con 60 ml VALVULAN'),
  ('Digoxina Solucion inyectable 0.5mg/2ml  ampolletas de 2ml'),
  ('Digoxina Tabletas 0.25 mg  LOTE: 231708'),
  ('Dobutamina Solucion inyectable 250 mg ampolletas c/5 ml DOBUJECT'),
  ('Dolutegravir tabletas 50 mg'),
  ('Dopamina Solucion inyectable 200 mg/5ml ampolletas c/5 ml'),
  ('Dopamina Solucion inyectable 200 mg/5ml ampolletas c/5 ml U00-03-02-2023-031102-F7'),
  ('Doxicilina solucion intravenosa 20mg/5ml, ampula con 5ml'),
  ('Doxorrubicina Solucion inyectable 10 mg'),
  ('Doxorrubicina Solucion inyectable 10 mg ZUCLODOX'),
  ('Doxorrubicina Solucion inyectable 50 mg'),
  ('Doxorrubicina Solucion inyectable 50 mg ZUCLODOX'),
  ('Doxorrubicina Suspension Inyectable 20 Mg (2 Mg/Ml)'),
  ('Electrolitos orales polvo para solucion envase con 27.9 g'),
  ('Emicizumab 150mg, Sol. Iny. ámpula con 1ml.'),
  ('Emtricitabina-Tenofovir disoproxil fumarato 200mg/300mg/245mg tableta recubierta'),
  ('Enalapril 10 mg o lisinopril 10 mg o Ramipril 10mg tabletas'),
  ('Enoxaparina Solucion inyectable 20 mg/ 0.2 ml 2 Jeringas de 0.2 ml'),
  ('Enoxaparina Solucion inyectable 40 mg/ 0.4 ml 2 Jeringas de 0.4 ml'),
  ('Epinefrina (Adrenalina) Solucion inyectable 1 mg (1:1 000) ampolletas de 1ml'),
  ('Eptacog Alta (factor de coagulacion VII alfa recombinante) 240 000 UI 5mg/5ml'),
  ('Ergometrina (ergonovina) Solucion inyectable 0.2mg/ml'),
  ('Eritromicina Suspension oral 250 mg/ 5 ml Envase con 100 ml'),
  ('Eritropoyetina humana recombinante S.I. 4 000 UI/ml frascos ampula o ampolletas'),
  ('Esmolol Solucion inyectable 2.5g/10ml ampolletas c/2ml'),
  ('Espironolactona tabletas 25 mg'),
  ('Estreptocinasa Solucion inyectable 750 000 UI/ 5 ml. c/ 5 ml'),
  ('Estreptomicina Solucion inyectable 1g  (c/agua inyectable c/2 ml)'),
  ('Estreptomicina Solucion inyectable 1g  (c/agua inyectable c/2 ml) IMSS'),
  ('Estrogenos conjugados de origen vegetal Grageas o tabletas 0.625 mg'),
  ('Etomidato Solucion inyectable 20mg/10ml ampolletas c/10ml'),
  ('Etoposido Solucion inyectable 100 mg ampolletas o frascos ampula c/5ml'),
  ('Etoposido Solucion inyectable 100 mg ampolletas o frascos ampula c/5ml IMSS'),
  ('Evolocumab 140 mg. Solucion inyectable. PLUMA prellenada con 1 ml. REPHATA'),
  ('Evolocumab 140 mg. Solución inyectable. JERINGA prellenada con 1 ml.'),
  ('Ezetimiba 10 mg tabletas'),
  ('Ezetimiba 10 mg tabletas IMSS'),
  ('Ezetimiba 10 mg tabletas RAAM'),
  ('Ezetimiba-Simvastatina, comprimido, 10mg/20mg PISA-PISATINE HC'),
  ('Faboterápico polivalente antialacran, Sol.Iny, Fco. ampula c/liofilizado y ampolleta c/diluyente 5ml'),
  ('Faboterápico polivalente antiarácnido para neutralizar 600 DL50 (120 glándulas de veneno)'),
  ('Faboterápico polivalente antiviperino Sol.Iny. Fco ampula c/liofilizado y ampolleta c/diluyente 10ml'),
  ('Factor VIII antihemofilico 500UI, Factor de Von Willdebrand 500UI. Solucion inyectable.'),
  ('Fenazopiridina Tabletas 100 mg'),
  ('Fenilefrina Solucion oftalmica 100 mg/ ml Envase con gotero integral c/15ml'),
  ('Fenitoina sodica (difenilhidantoina) tabletas o capsulas 100 mg'),
  ('Fenitoina sodica Solucion inyectable 250mg/5ml ampolleta con 5 ml'),
  ('Fenobarbital Tabletas 100 mg'),
  ('Fentanilo (Fentanil) Solucion inyectable 0.5mg/10ml ampolletas c/10 ml'),
  ('Filgrastim Solucion inyectable 300 µg/ml'),
  ('Finasterida Grageas 5mg'),
  ('Finasterida Grageas 5mg STERYX'),
  ('Fitomenadiona Solucion inyectable 10mg/ml Ampolletas c/1ml'),
  ('Fitomenadiona Solucion inyectable 2mg/ 0.2ml Ampolletas c/0.2ml PISA-UNOKAVI'),
  ('Flumazenil Solucion inyectable 0.5mg/5 ml ampolleta c/5ml'),
  ('Fluorouracilo Solucion inyectable 250 mg ampolletas c/10ml'),
  ('Fluorouracilo Solucion inyectable 250 mg ampolletas c/10ml ACOFLUT'),
  ('Fluoxetina Capsulas o tabletas 20mg NEOLPHARMA'),
  ('Fluticasona 50µg suspension en aerosol, frasco presurizado para 60 dosis'),
  ('Formula de proteinas hidrolizadas sin lactosa Polvo (Prot 12g, lip 17g, carbohid 51g) Env c/400-454g'),
  ('Fosaprepitant solucion inyectable 150mg'),
  ('Fosfato de Oseltamivir 45mg capsulas'),
  ('Fosfato de potasio S.I. Potasio dibasico 1.550g/10ml, potasio monofasico 0.300g/10ml amp. c/10ml'),
  ('Fosfolipidos de pulmón porcino 80mg, suspension, envase con 3ml'),
  ('Fumarato ferroso Suspension oral 29mg/ml Envase c/120 ml'),
  ('Fumarato ferroso Tabletas 200mg equivalente a 65.74 mg de hierro elemental.'),
  ('Furosemida Solucion inyectable 20mg/2ml Ampolletas c/2ml'),
  ('Furosemida Tabletas 40mg'),
  ('FÑE +43 ÑÑ +QWE +´Q W+´QW DL +'),
  ('Gabapentina Capsulas 300mg'),
  ('Ganciclovir Solucion inyectable 500mg frasco ampula y diluyente c/10ml'),
  ('Gelatina Solucion inyectable Polimerizado de gelatina succinilada degradada 4g/100ml 500 ml'),
  ('Gelatina Solucion inyectable Polimerizado de gelatina succinilada degradada 4g/100ml 500 ml PISA-GELAFUNDIN 4'),
  ('Gentamicina Solucion inyectable 20mg/2ml Ampolleta con 2ml'),
  ('Gentamicina Solucion inyectable 80mg/2ml ampolleta c/2ml'),
  ('Glibenclamida Tabletas 5mg'),
  ('Glicerina Supositorio adulto 2.632g'),
  ('Glimepirida tabletas 2 mg ADIRIPEM'),
  ('Gluconato de calcio Solucion inyectable al 10% 1g/10ml ampolletas c/10ml'),
  ('Glucosa Solucion inyectable al 10% Glucosa anhidra 10g/100ml 1000ml'),
  ('Glucosa Solucion inyectable al 10% Glucosa anhidra 10g/100ml 500ml'),
  ('Glucosa Solucion inyectable al 5% 5g/100ml 1000ml'),
  ('Glucosa Solucion inyectable al 5% 5g/100ml 250ml'),
  ('Glucosa Solucion inyectable al 5% 5g/100ml 500ml LOTE: P24U950'),
  ('Glucosa Solucion inyectable al 5% 5g/100ml 50ml'),
  ('Glucosa Solucion inyectable al 5% 5g/100ml 50ml (con adaptador para vial)'),
  ('Glucosa Solucion inyectable al 5% 5g/100ml. Envase c/100ml.'),
  ('Glucosa Solucion inyectable al 50% 50g/100ml 250ml'),
  ('Haloperidol Solucion inyectable 5 mg/ ml 6 ampolletas con un ml'),
  ('Haloperidol Tabletas 5 mg'),
  ('Heparina Solucion inyectable 10 000 UI/ 10 ml (1000 UI/ ml) Frascos ampula c/10ml'),
  ('Heparina Solucion inyectable 25 000 UI/ 5 ml   (5000 UI/ ml) Frascos ampula c/5ml'),
  ('Hidralazina Solucion inyectable 20 mg Ampolletas c/1ml'),
  ('Hidralazina Tableta 10 mg'),
  ('Hidroclorotiazida Tabletas 25 mg'),
  ('Hidroclorotiazida Tabletas 25 mg NEOLPHARMA'),
  ('Hidrocortisona (butirato de) Crema 1 mg/g Envase con 15 g'),
  ('Hidrocortisona S.I. 100mg/ 2ml Frascos ampula y diluyente de 2ml'),
  ('Hidroxicloroquina 200mg Tabletas.'),
  ('Hierro dextran Solucion inyectable 100 mg/ 2ml ampolletas con 2 ml'),
  ('Hipromelosa Solucion oftalmica 2% 20 mg/ml Envase con gotero integral 15ml'),
  ('Hipromelosa Solucion oftalmica al 0.5% 5 mg/ ml Envase con gotero integral con 15ml'),
  ('Ibuprofeno Solucion Inyectable 10mg/2ml'),
  ('Ibuprofeno capsulas o tabletas de 400 mg'),
  ('Ibuprofeno suspension oral, 2.0 gr, envase c/120 ml'),
  ('Ifosfamida Solucion inyectable 1g GENÉRICO'),
  ('Imatinib 400mg, comprimidos.'),
  ('Imatinib 400mg, comprimidos. GLIVEC'),
  ('Imipramina Grageas o tabletas 25 mg'),
  ('Indometacina Capsulas 25 mg'),
  ('Inmunoglobulina G no modificada. S.I. 6g/200ml fco amp y env. c/200ml de solvente'),
  ('Inmunoglobulina anti D Solucion inyectable 0.300mg/1.5 o 2ml (con o sin diluyente) F.Amp. ó Jeringa'),
  ('Insulina glargina 3.64 mg/ml. Frasco ampula 10 ml.'),
  ('Insulina humana accion intermedia NPH Suspension inyectable 100 UI/ml frasco ampula c/10 ml'),
  ('Ipratropio 0.50mg/salbutamol 2.mg, ampolleta 2.5ml'),
  ('Ipratropio 0.50mg/salbutamol 2.mg, ampolleta 2.5ml PISA VINZA'),
  ('Ipratropio solucion 0.25 mg/ml, frasco ampula con 20 ml'),
  ('Irinotecan Solucion inyectable 100mg'),
  ('Irinotecan Solucion inyectable 100mg CETABINDO'),
  ('Isoconazol Crema 1 g/ 100 g Envase con 20 g'),
  ('Isoconazol Crema 1 g/ 100 g Envase con 20 g FARMADEXTRUM'),
  ('Isosorbida dinitrato de  Tabletas 10 mg'),
  ('Isosorbida dinitrato de  Tabletas sublinguales 5 mg'),
  ('Ketoconazol Tabletas 200 mg'),
  ('Ketorolaco trometamina Solucion Inyectable 30mg Ampolletas 1 ml'),
  ('L-Ornitina L-Aspartato granulado 3g'),
  ('L-ornitina-l-aspartato 5gr. Solucion inyectable. Ampolletas de 10ml.'),
  ('Lacosamida 200mg/20ml solucion inyectable'),
  ('Lacosamida tabletas 100 mg'),
  ('Lenalidomida 10mg, cápsulas.'),
  ('Lenalidomida 15mg, cápsulas. ULDENALIV'),
  ('Lenalidomida 25mg, cápsulas.'),
  ('Leuprorelina 22.5mg Suspension inyectable'),
  ('Leuprorelina. Suspensión Inyectable 11.25 mg. Envase con frasco ámpula con 2 ml.'),
  ('Levetiracetam solucion oral 100 mg/ml, envase c/300ml'),
  ('Levetiracetam tabletas de 1000 mg'),
  ('Levodopa y carbidopa Tabletas 250 mg/ 25 mg'),
  ('Levosimendan 2.5mg/ml solucion inyectable'),
  ('Levotiroxina (Levotiroxina sodica) Tabletas 100µg'),
  ('Lidocaina Parche adhesivo 700mg. Sobre c/5 parches.'),
  ('Lidocaina Solucion al 10% 10g/100ml, frasco 115ml c/atomizador manual'),
  ('Lidocaina Solucion inyectable al 2% 1g/50ml, frasco ampula c/50ml'),
  ('Lidocaina con hidrocortisona Supositorio 60 mg/5 mg IMSS'),
  ('Lidocaina con hidrocortisona Ungüento 50 mg/1 g y 2.5 mg/1 g Envase c/20g y aplicador'),
  ('Lidocaina con hidrocortisona Ungüento 50 mg/1 g y 2.5 mg/1 g Envase c/20g y aplicador GENÉRICO'),
  ('Lidocaina y Epinefrina S.I. al 2% cartuchos dentales c/1.8 ml'),
  ('Lidocaina y Epinefrina S.I. al 2%, (20mg/0.005mg)  fcos ampula c/50ml'),
  ('Linagliptina 5mg tabletas'),
  ('Linagliptina/Metformina. Tabletas 2.5mg/850mg.'),
  ('Linezolid inyectable 200mg/300ml. Bolsa de 300ml.'),
  ('Linezolid tabletas de 600mg'),
  ('Lipidos intravenosos Emulsion iny. a 20% Lipidos intravenosos de cadena med. y larga  Env c/500ml'),
  ('Liraglutida solucion inyectable de 6 mg/ml, caja con 2 jeringas precargadas'),
  ('Loratadina Jarabe 5 mg/5 ml Envase con 60 ml'),
  ('Loratadina Jarabe 5 mg/5 ml Envase con 60 ml ALUDIX'),
  ('Loratadina Tabletas o grageas 10 mg'),
  ('Lorazepam Tabletas 1 mg'),
  ('Losartan potasico Grageas 50 mg'),
  ('Magnesio sulfato de Solucion inyectable 1g/10ml ampolletas c/10ml'),
  ('Magnesio sulfato de Solucion inyectable 1g/10ml ampolletas c/10ml PISA MAGNEFUSIN'),
  ('Manitol Solucion inyectable al 20% 50g/250ml Envase c/250 ml'),
  ('Medroxiprogesterona Comprimidos 10 mg'),
  ('Meloxicam Tabletas 15 mg'),
  ('Mercaptopurina Tabletas 50 mg'),
  ('Meropenem Solucion inyectable 1g'),
  ('Meropenem Solucion inyectable 500 mg'),
  ('Mesalazina 1gr. Supositorios.'),
  ('Mesalazina 6.667gr/100ml. Susp. rectal. Enema de 60ml.'),
  ('Mesilato de Imatinib, comprimido recubierto, 100 mg.'),
  ('Mesilato de Imatinib, comprimido recubierto, 100 mg.   GLIVEC'),
  ('Mesna Solucion inyectable 400mg/4ml ampolletas c/4ml'),
  ('Metadona 10 mg solucion oral, envase c/30 ml'),
  ('Metamizol sodico (Dipirona) Comprimidos 500 mg'),
  ('Metamizol sodico (Dipirona) Solucion inyectable 1g/2ml ampolletas c/2ml'),
  ('Metformina Tabletas 850 mg'),
  ('Metildopa (l-alfametildopa) Tabletas 250 mg'),
  ('Metilfenidato Comprimidos 10mg'),
  ('Metilprednisolona Solucion inyectable 500mg/8ml Ampolletas de 8ml'),
  ('Metilprednisolona Solucion inyectable 500mg/8ml Ampolletas de 8ml U00-03-02-2023-032193-ASF'),
  ('Metilprednisolona Suspension inyectable 40 mg/ ml frasco ampula c/2ml'),
  ('Metoclopramida Tabletas 10 mg'),
  ('Metoprolol Tabletas 100 mg'),
  ('Metotrexato  Solucion inyectable 500 mg / 20 ml'),
  ('Metotrexato  Solucion inyectable 500 mg / 20 ml TRAXACORD'),
  ('Metotrexato Tabletas 2.5 mg'),
  ('Metronidazol Solucion inyectable 200mg/10ml ampolletas c/10ml'),
  ('Metronidazol Solucion inyectable 500mg/100ml frasco ampula o bolsa c/100ml'),
  ('Metronidazol Suspension oral 250 mg/ 5 ml Envase con 120 ml'),
  ('Metronidazol Suspension oral 250 mg/ 5 ml Envase con 120 ml ELYZOL-S'),
  ('Metronidazol Tabletas 500 mg'),
  ('Metronidazol ovulos o tabletas vaginales 500 mg'),
  ('Midazolam Solucion inyectable 15mg/3ml. Ampolletas c/3ml'),
  ('Midazolam Solucion inyectable 50 mg ampolletas c/10ml'),
  ('Mifepristona 200mg. Tabletas. Envase c/1 tab.'),
  ('Milrinona 10mg/10ml solucion inyectable, Fco. Ampula c/10ml'),
  ('Mirtazapina tabletas 30 mg'),
  ('Misoprostol Tabletas 200 µg'),
  ('Mitoxantrona Solucion inyectable 20mg/10ml'),
  ('Mitoxantrona Solucion inyectable 20mg/10ml ZURICH PHARMA'),
  ('Mometasona suspension p/inhalacion, 0.050g. Envase c/18ml. (140 nebulizaciones de 50µg c/u)'),
  ('Montelukast granulado 4 mg envase c/10 sobres MAVER'),
  ('Morfina Solucion inyectable 10 mg/ml'),
  ('Morfina Tabletas  30 mg'),
  ('Moxifloxacino 400 mg tabletas'),
  ('Mupirocina Ungüento 2 g/100 g Envase con 15 g'),
  ('Nafazolina Solucion oftalmica 1 mg/ml Envase con gotero integral con 15 ml'),
  ('Nafazolina Solucion oftalmica 1 mg/ml Envase con gotero integral con 15 ml IMSS'),
  ('Nafazolina Solucion oftalmica 1 mg/ml Envase con gotero integral con 15 ml NAFAZOLINA'),
  ('Nalbufina Solucion inyectable 10 mg/ml'),
  ('Naloxona Solucion inyectable 0.4 mg/ ml ampolletas c/1ml'),
  ('Naproxeno Suspension oral 125 mg/ 5 ml Envase c/100ml'),
  ('Naproxeno Tabletas 250 mg'),
  ('Neomicina, polimixina B y acetonida de fluocinolona Sol. otica Envase c/gotero integral c/5ml'),
  ('Neomicina, polimixina B y bacitracina Ungüento oftalmico Envase con 3.5 g'),
  ('Neomicina, polimixina B y gramicidina (1.75mg/5000U/25µg ML) Sol. oftalmica. Env. c/gotero 15 ml'),
  ('Neostigmina Solucion inyectable 0.5 mg/ ml ampolletas c/1ml'),
  ('Nifedipino Capsulas de gelatina blanda 10 mg'),
  ('Nistatina ovulos o tabletas vaginales 100 000 UI'),
  ('Nistatina suspesion oral 2 400 000 UI envase para 24ml'),
  ('Nitazoxanida Tabletas 200 mg'),
  ('Nitrato de Miconazol crema 20 mg/1g (2%) envase c/20 g'),
  ('Nitrato de Miconazol crema 20 mg/1g (2%) envase c/20 g ALPHARMA'),
  ('Nitrofurantoina Capsulas 100 mg'),
  ('Nitrofurantoina Suspension oral 25 mg/ 5ml Envase con 120 ml'),
  ('Nitrofurazona ovulos 6mg'),
  ('Nitroprusiato de sodio Solucion inyectable 50 mg/ 2 ml frasco ampula c/2ml'),
  ('Norepinefrina (noradrenalina) Solucion inyectable 4 mg/4ml'),
  ('Obinutuzumab solución inyectable 1000mg envase con 40 ml'),
  ('Octreotida Solucion inyectable 1mg frasco ampula c/5ml'),
  ('Olanzapina Tabletas 10 mg RAAM'),
  ('Oligometales endovenosos (Zi, Cu, Ma, So, Y, F, Cl). Solucion inyectable. Frascos ampula c/20ml'),
  ('Omeprazol 20mg tab / cap / grageas'),
  ('Omeprazol Solucion inyectable 40 mg Frasco ampula o Ampolleta c/10ml'),
  ('Omeprazol Solucion inyectable 40 mg Frasco ampula o Ampolleta c/10ml FINULCER'),
  ('Ondansetron Solucion inyectable 8mg/4ml'),
  ('Ondansetron tabletas 8 mg'),
  ('Oxido de zinc (Lassar) Pasta 25 g/100 g  Envase con 30 g'),
  ('Oxitocina. Solucion inyectable. 5 UI/ ml ampolletas c/1ml'),
  ('Palivizumab 100mg. Solucion inyectable. Frasco ampula con 1.0 ml. SYNAGIS'),
  ('Palivizumab 50mg, solucion inyectable. Envase c/fco. ampula y diluyente. marca Astrazeneca'),
  ('Palonosetron 0.25mg/5l solucion inyectable, envase c/5 ml GESENT'),
  ('Pancreatina Capsulas o grageas con capa enterica 300 mg'),
  ('Pantopazol 40mg o Rabeprazol 20mg u Omeprazol 20mg. Tabletas o Capsulas.'),
  ('Paracetamol (Acetaminofen) Solucion oral 100 mg/ml Envase con gotero 15 ml'),
  ('Paracetamol (Acetaminofen) Tabletas 500 mg'),
  ('Paracetamol 1 g Frasco Inyectable 100 ml'),
  ('Paroxetina Tabletas 20 mg'),
  ('Pegaspargasa 3750UI/5mL solucion inyectable'),
  ('Pegaspargasa 3750UI/5mL solucion inyectable POLVO LIOFILIZADO DE 4,050UI (3,750UI EN 5ML, 750 UUML) SSA 010.000.7209.00'),
  ('Pegfilgrastim 6mg/0.6ml, jeringa prellenada'),
  ('Pegfilgrastim 6mg/0.6ml, jeringa prellenada PELGRAZ'),
  ('Pentoxifilina Tabletas o grageas de liberacion prolongada 400mg'),
  ('Pilocarpina Solucion oftalmica al 2% 20 mg/ ml Envase c/gotero integral c/15ml PIL OFTENO'),
  ('Pilocarpina Solucion oftalmica al 4% 40 mg/ ml Envase c/gotero integral c/15ml'),
  ('Pinaverio 100mg. Tabletas. Env. c/28 tabs.'),
  ('Pioglitazona 15 mg tabletas'),
  ('Piperacilina / Tazobactam 4g/500mg, Fco. Ampula c/polvo, sin diluyente'),
  ('Piperacilina / Tazobactam 4g/500mg, Fco. Ampula c/polvo, sin diluyente TAZOBACTAM'),
  ('Pirfenidona 600 mg tabletas'),
  ('Plantago psyllium Polvo 49.7 g Envase con 400 g'),
  ('Podofilino Solucion dermica. 250 mg/ml. Envase con 5 ml'),
  ('Polietilenglicol 105g polvo (sobres) IMSS'),
  ('Poligelina Solucion inyectable  3.5g/100ml 500ml'),
  ('Polivitaminas y Minerales Jarabe Vitaminas y minerales Envase con 240 ml'),
  ('Pramipexol tabletas 1mg'),
  ('Pravastatina Tabletas 10 mg'),
  ('Prednisolona Solucion oftalmica 5mg/ml Envase con gotero integral con 5 ml.'),
  ('Prednisona Tabletas 5 mg'),
  ('Prednisona Tabletas 50 mg'),
  ('Pregabalina 75 mg capsulas'),
  ('Propofol Emulsion iny 200 mg Sol c/aceite soya o lecitina huevo y glicerol Env c/5 Amp de 20 ml'),
  ('Propofol Emulsion inyectable 200 mg/20 ml ampolletas o frascos ampula c/20ml'),
  ('Propranolol Tabletas 40 mg'),
  ('Protamina Solucion inyectable 71.5mg/ 5ml ampolleta c/5ml'),
  ('Quetiapina tabletas 100 mg'),
  ('Quetiapina tabletas 300 mg'),
  ('Raloxifeno tabletas 60 mg'),
  ('Raloxifeno tabletas 60 mg ULOS-H'),
  ('Resina de colestiramina polvo 4g, sobre'),
  ('Rifaximina 200mg. Tabletas.'),
  ('Risperidona 25 mg. Envase con frasco ampula y jeringa prellenada con 2 ml de diluyente'),
  ('Risperidona Tabletas 2 mg'),
  ('Rituximab 100mg/10ml solucion inyectable, envase c/2 fcos ampulas de 10 ml'),
  ('Rituximab Solucion inyectable 500mg Envase c/50ml con dos frasco ampula'),
  ('Rocuronio Solucion inyectable 50 mg/5 ml'),
  ('Romiplostim 375µg ampula'),
  ('Ropivacaina 150mg/20ml ampolletas de 20 ml'),
  ('Rosuvastatina tabletas 10mg'),
  ('Rosuvastatina tabletas 10mg AMSA'),
  ('Ruxolitinib tableta 20 mg'),
  ('Sacubitrilo valsartan 100mg. Comprimidos.'),
  ('Salbutamol Jarabe 2 mg/ 5 ml Envase con 60 ml'),
  ('Salbutamol Solucion para respiradores(nebulizadores) 0.5g/100 ml Envase c/10ml'),
  ('Salbutamol suspension aerosol 20mg envase c/inhalador c/200 dosis de 100 µg'),
  ('Salmeterol 50g / Fluticasona 100g /dosis, polvo. Dispositivo inhalador para 60 dosis'),
  ('Secukinumab Solucion inyectable 150g. Env. c/2 plumas precargadas con 1ml.'),
  ('Semaglutida Tabletas 3mg. GLP-1 de origen ADN recombinante.'),
  ('Senosidos A-B Tabletas  8.6mg'),
  ('Seroalbumina humana Solucion inyectable 10 g/50ml  50 ml'),
  ('Seroalbumina humana Solucion inyectable 12.5g/50ml  50 ml'),
  ('Seroalbumina humana Solucion inyectable 12.5g/50ml  50 ml OCTALBIN'),
  ('Sertralina Capsulas 50 mg PISA-EQUIVAC'),
  ('Sevoflurano Liquido 250 ml Envase con 250 ml'),
  ('Sevoflurano Liquido 250 ml Envase con 250 ml PISA FLOVES'),
  ('Sildenafil tabletas 20mg.'),
  ('Sildenafil tabletas 50 mg'),
  ('Simoctocog alfa, sol. iny. 1000 UI, frasco ampula con polvo liofilizado'),
  ('Simoctocog alfa, sol. iny. 500UI, frasco ampula con polvo liofilizado'),
  ('Sitagliptina 50mg (Fosfato). Comprimidos'),
  ('Sitagliptina 50mg (Fosfato). Comprimidos BITAM'),
  ('Sitagliptina comprimidos 100 mg'),
  ('Sitagliptina comprimidos 100 mg JANUVIA'),
  ('Sitagliptina con metformina. Comprimidos 50mg/850mg'),
  ('Solucion Hartmann 1000 ml'),
  ('Solucion Hartmann 500 ml'),
  ('Sucedaneo de leche humana de pretermino polvo P:15g, L:29g, C:57g Env. c/400 a 454g'),
  ('Sucralfato Tabletas 1g'),
  ('Sulfadiazina de plata micronizada Crema 1g/100g. Envase con 375 g'),
  ('Sulfasalazina Tableta con capa enterica 500mg ANDAGUN'),
  ('Sulfato ferroso Solucion oral 125 mg/ ml Envase gotero c/15ml GENÉRICO'),
  ('Sulfato ferroso Tabletas 200 mg'),
  ('Tadafil Tableta 20mg.'),
  ('Tamsulosina Capsula de Liberacion Prolongada 0.4 mg'),
  ('Telmisartan 40 mg  Tabletas'),
  ('Telmisartan 80mg / Hidroclorotiazida 12.5 mg tabletas'),
  ('Temozolomida 100 mg capsulas'),
  ('Tenecteplasa sol. iny. 50mg (10,000 U), Fco. Amp y Jeringa Prellenada c/10 ml de agua inyectable'),
  ('Tenecteplasa sol. iny. 50mg (10,000 U), Fco. Amp y Jeringa Prellenada c/10 ml de agua inyectable METALYSE'),
  ('Teofilina Comprimidos, tabs o capsulas de liberacion prolongada 100 mg. ALPHARMA'),
  ('Tetracaina Solucion oftalmica 5 mg/ ml Envase con gotero integral c/10ml'),
  ('Tetracaina Solucion oftalmica 5 mg/ ml Envase con gotero integral c/10ml PONTI OFTENO'),
  ('Tetracaina Solucion oftalmica 5 mg/ ml Envase con gotero integral c/10ml TETRACAINA'),
  ('Tiamazol Tabletas 5 mg'),
  ('Tiamazol Tabletas 5 mg U00-03-02-2023-031731-ASF'),
  ('Tiamina Solucion inyectable 500 mg'),
  ('Tigeciclina Solucion inyectable 50mg.'),
  ('Timolol Solucion oftalmica 5mg/ml Envase c/gotero integral c/5ml'),
  ('Tobramicina 300mg/5ml. Solucion p/nebulizar. Env c/14 sobres de 4 amp c/u.'),
  ('Tobramicina Solucion oftalmica 3mg/ml Envase con gotero integral c/15 ml TRAZIL OFTENO'),
  ('Topiramato Tabletas 100 mg'),
  ('Tramadol 150mg. Tabletas de liberacion prolongada.'),
  ('Tramadol 37.5mg / Paracetamol 325mg, tabletas'),
  ('Tramadol solucion gotas, frasco c/10 ml'),
  ('Tretinoina Capsulas 10 mg'),
  ('Trihexifenidilo Tabletas 5 mg'),
  ('Trimetoprima y sulfametoxazol Suspension oral 40mg/200mg/5ml Envase con 120 ml'),
  ('Trimetoprima y sulfametoxazol Tabletas 80mg/400mg U00-03-02-2023-031742-ASF'),
  ('Trinitrato de glicerilo Parche 5mg/dia'),
  ('Trinitrato de glicerilo Solucion inyectable 50mg/10ml Envase c/10ml'),
  ('Tropicamida 1g/100ml + fenilefrina 100mg/ml  solucion oftalmica envase c/15ml'),
  ('Tropicamida Solucion oftalmica 1 g/100 ml Envase con gotero integral c/5ml'),
  ('Valproato de magnesio 200mg (185.6mg ácido valproico) Tabletas con cubierta enterica'),
  ('Valproato de magnesio Solucion oral 186 mg/ ml Envase con 40 ml'),
  ('Valproato semisodico (acido valproico) 250mg, comprimido c/capa enterica'),
  ('Vancomicina Solucion inyectable 500 mg'),
  ('Vancomicina Solucion inyectable 500 mg ALVARCIN'),
  ('Vasopresina Solucion inyectable 20 UI'),
  ('Vecuronio Solucion inyectable 4mg/ml ampolletas o frascos ampula c/1ml U00-03-02-2023-031238-ASF'),
  ('Vecuronio Solucion inyectable 4mg/ml ampolletas o frascos ampula c/1ml U00-03-02-2023-032222-ASF'),
  ('Venetoclax 100 mg. Tabletas.'),
  ('Venlafaxina 75mg capsulas o gragea de liberacion prolongada'),
  ('Verapamilo Gragea o Tableta recubierta 80 mg'),
  ('Verapamilo Solucion inyectable 5mg/2ml ampolleta c/2ml'),
  ('Vigabatrina comprimidos 500 mg'),
  ('Vinblastina Solucion inyectable 10 mg. Incluye ampolleta con 10ml de diluyente.'),
  ('Vincristina 1 mg. Solucion inyectable. Liofilizado.'),
  ('Vincristina Solucion inyectable 1mg/10ml (diluyente c/10 ml)'),
  ('Vincristina Solucion inyectable 1mg/10ml (diluyente c/10 ml) SUTIVIN'),
  ('Vincristina solución inyectable fco amp 1mg/10ml (diluyente 10ml)'),
  ('Vitamina A Solucion oral 200 000 UI Envase con 25 dosis'),
  ('Vitaminas  A, C y D Solucion oral Envase con 15 ml.'),
  ('Voriconazol Solucion inyectable 200mg.'),
  ('Voriconazol tabletas de 200mg'),
  ('Warfarina Tabletas 5 mg'),
  ('Zidovudina Sol. Inyectable 200mg/20ml'),
  ('Zuclopentixol Solucion inyectable 200 mg');
