-- ============================================================
-- ACTUALIZAR CATALOGO DE MEDICAMENTOS  (Cuadro Basico IMSS-Bienestar 29-may-2026)
-- 659 medicamentos. Idempotente. Correr en el SQL Editor de Supabase.
-- ------------------------------------------------------------
-- * Desactiva el catalogo GENERAL viejo (grupo_control IS NULL).
-- * NO toca los CONTROLADOS (grupo_control IS NOT NULL): el dropdown de
--   recetas controladas queda intacto.
-- * UPSERT de la lista nueva: inserta los que falten y reactiva (activo=true)
--   los que ya existieran (incluye reactivar un controlado si su nombre coincide).
-- ============================================================
BEGIN;

-- 1) Apagar catalogo general viejo (preserva controlados)
UPDATE catalogo_medicamentos SET activo = false WHERE grupo_control IS NULL;

-- 2) Alta/Reactivacion de los 659 del cuadro basico nuevo
INSERT INTO catalogo_medicamentos (nombre, activo) VALUES
  ('Aceite de almendras e hidroxido de calcio Crema. Envase 240 ml', true),
  ('Acenocumarol (acenocumarina) Tableta 4 mg', true),
  ('Acetazolamida Tabletas 250 mg', true),
  ('Acetilcisteina Solucion esteril 20% 400 mg /2 ml Ampolleta 2 ml', true),
  ('Aciclovir Comprimidos 200 mg', true),
  ('Aciclovir Solucion inyectable 250 mg', true),
  ('Aciclovir Tabletas 400 mg', true),
  ('Aciclovir Ungüento oftalmico 3 g/ 100 g Envase con 4.5 g.', true),
  ('Acido acetilsalicilico Tableta soluble o efervecente 300 mg', true),
  ('Acido acetilsalicilico Tabletas 100 mg', true),
  ('Acido acetilsalicilico Tabletas 500 mg', true),
  ('Acido alendronico (alendronato) 10 mg. Tabletas o caps.', true),
  ('Acido alendronico 70mg, tableta o comprimido', true),
  ('Acido ascorbico Tabletas 100 mg', true),
  ('Acido folico Tabletas 0.4 mg', true),
  ('Acido folico tabletas 5 mg', true),
  ('Acido folinico Solucion inyectable 15 mg/5 ml ampolletas con 5 ml', true),
  ('Acido folinico Solucion inyectable 50 mg ampolleta con 4 ml', true),
  ('Acido folinico Tabletas 15 mg', true),
  ('Acido micofenolico (micofenolato mofetilo). Comprimido 500 mg', true),
  ('Acido micofenolico Gragea con capa enterica o tableta de liberacion prolongada 180mg', true),
  ('Acido retinoico Crema 500 µg/ g Envase con 20 g', true),
  ('Acido Tranexamico 100mg/ml, solucion inyectable. Ampula de 5ml.', true),
  ('Acido Ursodeoxicolico Tabletas 500mg', true),
  ('Acido valproico 250mg, capsulas', true),
  ('Acido zoledronico solucion inyectable 4mg/5ml', true),
  ('Adenocina Sol. Iny. 6mg/2ml Frasco ampula c/2ml', true),
  ('Aflibercept solucion inyectable 40mg. Frasco ampula co 0.278ml (40mg/ml)', true),
  ('Agua inyectable Solucion inyectable 10 ml', true),
  ('Agua inyectable Solucion inyectable 500 ml', true),
  ('Albendazol Suspension oral 20 mg/ml Envase con 20 ml', true),
  ('Albendazol Tabletas 200 mg', true),
  ('Alfa cetoanalogos de aminoacidos Grageas 630 mg', true),
  ('Alfadornasa Solucion inyectable 2.5 mg. Ampolleta con 2.5 ml', true),
  ('Alibour Polvo Cobre 177 mg/g ,zinc 619.5 mg/g alcanfor 26.5 mg/g 12 sobres con 2.2 g', true),
  ('Alopurinol Tabletas 300 mg', true),
  ('Alprazolam 0.5 mg', true),
  ('Alprazolam Tabletas 0.25 mg', true),
  ('Alprostadil solucion inyectable de 500 mcg/ml, ampolletas', true),
  ('Alteplasa (activador tisular de plasminogeno humano) 50 mg sol. iny.', true),
  ('Aluminio y magnesio susp oral hidroxido Al 3.7g, hidroxido Mg 4g o trisilicato Mg 8.9g env c/240ml', true),
  ('Aluminio y magnesio Tabletas masticables Al 200 mg, Mg 200 o 447.3 mg', true),
  ('Ambroxol Comprimidos 30 mg', true),
  ('Ambroxol Solucion oral 300 mg/ 100 ml Envase con 120 ml', true),
  ('Amfotericina B liposomal solucion inyectable 50mg. Liofilizado con o sin diluyente 12ml.', true),
  ('Amfotericina B Solucion inyectable 50 mg', true),
  ('Amikacina 500mg. Solucion intyectable. Envase c/2 ampolletas.', true),
  ('Amikacina Solucion inyectable 100 mg/ 2 ml', true),
  ('Amikacina Solucion inyectable 500 mg/ 2 ml', true),
  ('Aminoacidos con electrolitos. Solucion inyectable al 8.5% Envase 500 ml.', true),
  ('Aminoacidos cristalinos Solucion inyectable al 10% Pediatricos Envase con 250 ml', true),
  ('Aminoacidos cristalinos. Solucion inyectable al 10% Adultos Envase con 500 ml', true),
  ('Aminofilina Solucion inyectable 250 mg/ 10 ml ampolletas con 5 ml', true),
  ('Amiodarona Solucion inyectable 150 mg ampolletas con 3 ml', true),
  ('Amiodarona Tabletas 200 mg', true),
  ('Amitriptilina Tabletas 25 mg', true),
  ('Amlodipino 5mg. Tableta o capsula.', true),
  ('Amlodipino/Valsartan/Hidroclorotiazida comprimidos 5mg/160mg/12.5mg', true),
  ('Amoxicilina 500mg / acido clavulanico 125 mg tabletas', true),
  ('Amoxicilina 875mg / acido clavulanico 125mg tabletas', true),
  ('Amoxicilina Suspension oral 500 mg/ 5 ml Envase con 75 ml', true),
  ('Amoxicilina/ acido clavulanico Solucion inyectable 500 mg/ 100 mg. Frasco ampula con o sin 10 ml', true),
  ('Amoxicilina/ acido clavulanico Suspension oral 125 mg/ 5 ml Envase con 60 ml', true),
  ('Ampicilina Solucion inyectable 500mg/2ml Frasco ampula y diluyente 2 ml', true),
  ('Ampicilina Suspension oral 250 mg/ 5 ml Envase con 60 ml', true),
  ('Ampicilina Tabletas o capsulas 500 mg', true),
  ('Anestesia suggamadex Solucion inyectable 200mg/2ml. Frasco ampula 2 ml.', true),
  ('Apixaban 2.5mg. Tabletas.', true),
  ('Apixaban tabletas 5mg.', true),
  ('Aprepitant, 1 capsula 125mg, 2 capsulas de 80mg', true),
  ('Aripiprazol tabletas de 15 mg', true),
  ('Atorvastatina 20mg. Tabletas', true),
  ('Atorvastatina tabletas 20 mg', true),
  ('Atorvastatina/Ezetimiba Capsulas o tabletas 40mg/10mg', true),
  ('Atosiban, solucion inyectable, 6.75mg/0.9ml, envase c/0.9ml', true),
  ('Atropina Solucion inyectable 1 mg/ml', true),
  ('Atropina Solucion oftalmica 10 mg/ ml Envase con gotero integral con 15 ml', true),
  ('Azacitidina 100mg solucion inyectable', true),
  ('Azatioprina Tabletas 50 mg', true),
  ('Azitromicina suspencion 200mg/5ml, polvo para reconstituir 10ml', true),
  ('Azitromicina tabletas de 500 mg', true),
  ('Baño coloide polvo harina de soya 965 mg/g polividona 20 mg/g c/2 Sobres con 90 g', true),
  ('Beclometasona dipropionato de Aerosol 0.0587 g/ 100 g Inhalador con 200 dosis de 50 µg', true),
  ('Beclometasona dipropionato de Suspension aerosol 0.294 g/100 g Inhalador con 200 dosis de 250 µg', true),
  ('Beclometazona 100µg / Formoterol 6µg / Glicopirronio 12.5µg, frasco c/120 dosis e inhalador', true),
  ('Bencilpenicilina procainica c/bencilpenicilina cristalina S.I. 300,000UI/100,000UI (diluyente c/2ml)', true),
  ('Bencilpenicilina procainica c/bencilpenicilina cristalina S.I. 600 000UI/200 000UI (diluyente c/2ml)', true),
  ('Bencilpenicilina sodica cristalina Sol iny 1 000 000 UI (con diluyente)', true),
  ('Bencilpenicilina sodica cristalina Solucion inyectable 5 000 000 UI', true),
  ('Bendamustina 100mg, ámpula.', true),
  ('Benralizumab jeringa prellenada con dosis única de 30mg/ml', true),
  ('Benzatina bencilpenicilina Suspension inyectable 1 200 000 UI (diluyente c/5ml)', true),
  ('Benzonatato Perlas 100 mg', true),
  ('Beractant (fosfolipidos de pulmon) susp. iny. 25 mg/ml frasco ampula c/8ml', true),
  ('Besilato de cisatracurio 2mg/ml Solucion inyectable. Envase c/5ml', true),
  ('Betametasona (dipropionato de) Ungüento 50 mg/100g Envase c/30g', true),
  ('Betametasona Solucion inyectable 4 mg/ ml frasco ampula', true),
  ('Bevacizumab 100 mg Solución Inyectable. Frasco ámpula con 4 ml.', true),
  ('Bezafibrato Tabletas 200 mg', true),
  ('Bicalutamida Tabletas 50 mg', true),
  ('Bicarbonato de sodio Solucion inyectable al 7.5% 0.75 g/10 ml. Envase c/10 ml', true),
  ('Bicarbonato de sodio Solucion inyectable al 7.5% 3.75 g/50 ml envase c/50 ml', true),
  ('Biperideno Tabletas 2 mg', true),
  ('Bismuto subsalicilato de Suspension oral 1.750g/100ml Envase con 240ml', true),
  ('Bisoprolol tabletas 5mg', true),
  ('Bleomicina Solucion inyectable 15 UI Frasco ampula y diluyente c/5 ml', true),
  ('Bleomicina solucion inyectable 15UI Frasco ampula y diluyente c/10 ml', true),
  ('Blinatumomab solucion inyectable fco amp con liofilizado con 35mcg', true),
  ('Bortezomib Solucion Inyectable 3.5mg. Liofilizado.', true),
  ('Bosentan tabletas de 125 mg', true),
  ('Brentuximab vedotin 50mg S.I.', true),
  ('Bromuro de ipratropio/Fenoterol aerosol 0.394mg/0.938mg. Frasco presurizado c/inhalador', true),
  ('Bromuro de Tiotropio, capsula 18 µg (repuesto)', true),
  ('Bromuro de Tiotropio, capsula 18 µg con dispositivo inhalador', true),
  ('Budesonida (micronizada) 0.250 mg, suspension en aerosol, envase c/2ml en sobre de aluminio', true),
  ('Budesonida (micronizada) polvo, envase c/200 dosis y dispositivo inhalador', true),
  ('Budesonida 180mg / formloterol 5mg envase c/frasco inhalador dosificador c/60 dosis 160µg/4.5µg c/u', true),
  ('Budesonida aerosol p/inhalación bucal, 4.285mg/g env c/200 dosis de 200µg c/u + disp inhalador', true),
  ('Budesonida suspensión para Inhalación. 1.280mg/ml. Frasco con 6 ml (120 dosis de 64µg c/u)', true),
  ('Bumetanida Tabletas o Capsulas 1mg.', true),
  ('Bupivacaina hiperbarica Solucion inyectable Bupivacaina 15 mg/ml Dextrosa 240 mg. ampolletas c/3ml', true),
  ('Bupivacaina Solucion inyectable 150 mg/30ml (5mg/ml). Envase c/30ml', true),
  ('Buprenorfina parche 10mg.', true),
  ('Buprenorfina parche 20 mg', true),
  ('Buprenorfina parche 30 mg', true),
  ('Buprenorfina Solucion inyectable 0.30mg/ml. frasco ampula c/1ml', true),
  ('Bupropion 150 mg, tabletas de liberacion prolongada', true),
  ('Butilhioscina Grageas 10mg', true),
  ('Butilhioscina Solucion inyectable 20mg/ ml. Ampolletas c/1ml', true),
  ('Butilhioscina/metamizol Grageas 10 mg/250mg', true),
  ('Calcio Comprimidos efervescentes 500mg', true),
  ('Calcitriol (1 alfa 25 dihidroxicolicolecalciferol) Capsulas de gelatina blanda 0.25µg', true),
  ('Carbamazepina Susp. oral 100 mg/5ml. Envase c/120 ml y vaso dosificador de 5ml, adosado al envase', true),
  ('Carbamazepina Tabletas 200 mg', true),
  ('Carbetocina, solucion inyectable 100µg', true),
  ('Carbon activado Polvo', true),
  ('Carbonato de calcio 600mg/Vitamina D3 62.mg. Tabletas.', true),
  ('Carboplatino Solucion inyectable 150 mg', true),
  ('Carboplatino Solucion Inyectable 450mg. Liofilizado', true),
  ('Carboximaltosa ferrica solucion inyectable 500mg envase c/10 ml', true),
  ('Carvedilol 25mg. Tabletas.', true),
  ('Carvedio tableta 6.250', true),
  ('Caseinato de calcio Polvo Proteinas 90g, lipidos 2g Envase c/100g.', true),
  ('Caspofungina 50 mg, Solución Inyectable. Envase con polvo para10.5 ml (7mg/ml)', true),
  ('Cefalexina Capsulas o tabletas 500 mg', true),
  ('Cefalotina Solucion inyectable 1g/5ml (diluyente c/5ml)', true),
  ('Cefepima Solucion inyectable 1g (diluyente c/10ml)', true),
  ('Cefixima 100mg/5ml. Suspension oral. Frasco para 100ml. Con pipeta dosificadora', true),
  ('Cefixima capsulas 400mg.', true),
  ('Cefotaxima Solucion inyectable 1g/4ml (diluyente c/4ml)', true),
  ('Ceftazidima Solucion inyectable 1g (diluyente c/3ml)', true),
  ('Ceftazidima-Avibactam 200mg/500mg. Solucion para perfusion. Frascos viales con polvo.', true),
  ('Ceftriaxona Solucion inyectable 1g/10ml (diluyente c/10ml)', true),
  ('Celecoxib Capsulas 100mg', true),
  ('Celecoxib Capsulas 200mg', true),
  ('Ciclofosfamida Solucion inyectable 500 mg', true),
  ('Ciclopentolato Solucion oftalmica 10 mg/ml. Envase con gotero integral c/3ml', true),
  ('Ciclosporina A Solucion o Emulsion oral 100 mg/ml frasco 50 ml y pipeta dosificadora', true),
  ('Cilostazol tableta 100mg', true),
  ('Cinitaprida (Bitartrato) Comprimido 1 mg', true),
  ('Cinitaprida (Bitartrato) Solución oral 20 mg/100 ml (1 mg/5 ml) Envase con 120 ml y cucharita dosifi', true),
  ('Cinitaprida granulado 1mg, sobre', true),
  ('Ciprofloxacino Solucion oftalmica 0.300g/100ml Envase con gotero integral c/5ml', true),
  ('Ciprofloxacino suspension 250mg/5ml, envase c/5g y 93ml de diluyente', true),
  ('Ciprofloxacino Tabletas o capsulas 250 mg', true),
  ('Cisplatino Solución inyectable 10mg, Frasco ampula c/10ml', true),
  ('Cisplatino solucion inyectable 10mg. Frasco ampula c/20ml', true),
  ('Citarabina Solucion inyectable 500 mg/ 10 ml frasco ampula c/10ml', true),
  ('Citrato de cafeina 20mg. Solucion Inyectable. Envase c/10 frascos amp. de 1ml.', true),
  ('Claritromicina Solucion inyectable 500mg. Envase con frasco ampula', true),
  ('Claritromicina Suspension 2.50gr. Frasco con 60ml.', true),
  ('Claritromicina Tabletas 250 mg', true),
  ('Claritromicina Tabletas 500 mg', true),
  ('Clindamicina Capsulas 300 mg', true),
  ('Clindamicina Solucion inyectable 300mg/2ml ampolleta c/2ml', true),
  ('Clioquinol (Yodoclorohidroxiquinoleina) Crema 30 mg/g Envase con 20 g', true),
  ('Clonazepam Solucion oral 2.5 mg/ ml Envase con 10 ml y gotero integral', true),
  ('Clonazepam Tabletas 2 mg', true),
  ('Clonixinato de lisina Solucion inyectable 100 mg/2ml', true),
  ('Clopidogrel Grageas 75 mg', true),
  ('Clorambucilo Tabletas 2 mg', true),
  ('Cloramfenicol Ungüento oftalmico 5 mg/g Envase con 5 g', true),
  ('Cloranfenicol Solucion oftalmica 5 mg/ml Envase con gotero integral con 15 ml', true),
  ('Clorfenamina (Clorfeniramina) Tabletas 4 mg', true),
  ('Clorfenamina compuesta Tabletas Paracetamol 500mg, cafeina 25mg, fenilefrina 5mg, clorfenamina 4mg', true),
  ('Clorhidrato de Dexrazoxano, solución inyectable, 500 mg', true),
  ('Cloroquina Tabletas 150 mg', true),
  ('Clortalidona Tabletas 50 mg', true),
  ('Cloruro de potasio Solucion inyectable 1.49g/10ml. ampolletas c/10ml', true),
  ('Cloruro de sodio 50 mg. Pomada o Solución oftalmica. Env 7gr ó Gotero 10ml', true),
  ('Cloruro de sodio al 9% y Glucosa al 5%, solucion inyectable, envase c/1000 ml', true),
  ('Cloruro de sodio al 9% y Glucosa al 5%, solucion inyectable, envase c/250 ml', true),
  ('Cloruro de sodio al 9% y Glucosa al 5%, solucion inyectable, envase c/500 ml', true),
  ('Cloruro de sodio Solucion inyectable al 0.9% 100 ml', true),
  ('Cloruro de sodio Solucion inyectable al 0.9% 1000 ml', true),
  ('Cloruro de sodio Solucion inyectable al 0.9% ampolletas con 10 ml', true),
  ('Cloruro de sodio Solucion inyectable al 17.7% ampolletas con 10 ml', true),
  ('Cloruro de Suxametonio (Succinilcolina) Sol. Iny. 40mg/2ml ampolletas c/2ml', true),
  ('Clozapina Comprimidos 100 mg', true),
  ('Colchicina Tabletas 1 mg', true),
  ('Colistemitato de sodio solucion inyectable 150mg/2ml', true),
  ('Complejo B Tabletas o capsulas Tiamina 100 mg, piridoxina 5 mg, cianocobalamina 50 µg', true),
  ('Complejo coagulante anti-inibidor del factor VIII Sol. Iny. 500 UFEIBA. Proteina P Humana 200-600mg', true),
  ('Cromoglicato de sodio Solucion oftalmica 40 mg/ml Envase c/gotero integral c/5ml', true),
  ('Dabigatran etexilato Capsulas110 mg,', true),
  ('Dacarbazina Solucion inyectable 200 mg', true),
  ('Dactinomicina (actinomicina D) Solucion inyectable 0.5mg', true),
  ('Danazol Capsulas o comprimidos 100 mg', true),
  ('Dapagliflozina 10mg / Metformina 1000mg tabletas', true),
  ('Dapagliflozina propanodiol equivalente a 10 mg de dapagliflozina', true),
  ('Dasatinib tabletas 50 mg', true),
  ('Daunorubicina Solucion inyectable 20 mg', true),
  ('Deferasirox comprimidos 500mg', true),
  ('Denosumab 60mg, jeringa prellenada con 1ml.', true),
  ('Desfluorano liquido envase c/240 ml', true),
  ('Desmopresina solucion inyectable 15µg/ml,', true),
  ('Desmopresina Solucion nasal 89 µg/ ml Envase nebulizador c/2.5 ml.', true),
  ('Dexametasona solucion inyectable 8 mg/2ml ampolleta c/2ml', true),
  ('Dexametasona Solucion oftalmica. 0.1g/100ml Envase c/gotero integral c/5ml', true),
  ('Dexametasona Tabletas 0.5 mg', true),
  ('Dexmedetomidina 200µg solucion inyectable. Envase c/25 frascos ampula', true),
  ('Diazepam Solucion inyectable 10 mg/2 ml ampolletas c/2ml', true),
  ('Diazepam Tabletas 10 mg', true),
  ('Diclofenaco Capsula o gragea de liberacion prolongada 100 mg', true),
  ('Diclofenaco Solucion inyectable 75mg/3ml ampolletas c/3ml', true),
  ('Diclofenaco Solucion oftalmica 1 mg/ml Envase con gotero integral con 5 ml', true),
  ('Dicloxacilina Capsulas o comprimidos 500 mg', true),
  ('Dicloxacilina Suspension inyectable 250 mg/5ml (diluyente c/5ml)', true),
  ('Dicloxacilina Suspension oral 250 mg/ 5 ml Envase con 60 ml', true),
  ('Dieta elemental. Polvo Proteinas, lipidos, carbohidratos. Pqte c/6 sobres de 80.4g c/u', true),
  ('Dieta polimerica a base de caseinato de calcio Polvo Env c/400 a 454g con o sin sabor', true),
  ('Dieta polimerica s/fibra Susp. oral Prot, lip, carb Envase con 236 o 250 ml', true),
  ('Difenhidramina Jarabe 12.5 mg/ 5 ml Envase con 60 ml', true),
  ('Difenhidramina Solucion inyectable 100mg/10ml frasco ampula c/10ml.', true),
  ('Difenidol Solucion inyectable 40mg/2ml ampolletas c/2ml', true),
  ('Difenidol Tabletas 25 mg', true),
  ('Digoxina Elixir 0.05 mg/ml Envase con 60 ml', true),
  ('Digoxina Solucion inyectable 0.5mg/2ml ampolletas de 2ml', true),
  ('Digoxina Tabletas 0.25 mg', true),
  ('Dinoprostona (prostaglandina E2) Jeringa con gel 0.5 mg envase con jeringa y canula', true),
  ('Dobutamina Solucion inyectable 250 mg ampolletas c/5 ml', true),
  ('Donepecilo Tabletas 10mg.', true),
  ('Dopamina Solucion inyectable 200 mg/5ml ampolletas c/5 ml', true),
  ('Doxiciclina Capsulas o tabletas 100 mg', true),
  ('Doxorrubicina Solucion inyectable 10 mg', true),
  ('Doxorrubicina Solucion inyectable 50 mg', true),
  ('Doxorrubicina Suspension Inyectable 20 Mg (2 Mg/Ml)', true),
  ('Duloxetina Capsulas 60 mg', true),
  ('Dutasterida capsulas 0.5mg', true),
  ('Efedrina Solucion inyectable 50 mg/2 ml ampolletas c/2ml', true),
  ('Electrolitos orales (formula de osmolaridad baja) polvo, envase c/20.5 gr', true),
  ('Electrolitos orales polvo para solucion envase con 27.9 g', true),
  ('Eletriptan tableta 80mg', true),
  ('Emicizumab 150mg, Sol. Iny. ámpula con 1ml.', true),
  ('Enalapril 10 mg o lisinopril 10 mg o Ramipril 10mg tabletas', true),
  ('Enoxaparina Solucion inyectable 20 mg/ 0.2 ml 2 Jeringas de 0.2 ml', true),
  ('Enoxaparina Solucion inyectable 40 mg/ 0.4 ml 2 Jeringas de 0.4 ml', true),
  ('Enoxaparina Solucion inyectable 60 mg/ 0.6 ml 2 Jeringas de 0.6 ml', true),
  ('Enoxaparina Solucion Inyectable 80 mg/0.8 ml 2 jeringas de 0.8 ml', true),
  ('Enzalutamida 40 mg. Capsulas', true),
  ('Epinefrina (Adrenalina) Solucion inyectable 1 mg (1:1 000) ampolletas de 1ml', true),
  ('Eptacog Alta (factor de coagulacion VII alfa recombinante) 240 000 UI 5mg/5ml', true),
  ('Ergometrina (ergonovina) Solucion inyectable 0.2mg/ml', true),
  ('Eritromicina Capsulas o tabletas 500 mg', true),
  ('Eritromicina Suspension oral 250 mg/ 5 ml Envase con 100 ml', true),
  ('Eritropoyetina humana recombinante S.I. 2 000 UI/ml fco. amp. o ampolletas c/ o s/ diluyente', true),
  ('Eritropoyetina humana recombinante S.I. 4 000 UI/ml frascos ampula o ampolletas', true),
  ('Ertapenem Solucion inyectable 1gr. Frasco ampula con liofilizado', true),
  ('Escitalopram 10 mg tabletas', true),
  ('Esmolol Solucion inyectable 2.5g/10ml ampolletas c/2ml', true),
  ('Esomeprazol 40mg. Tabletas.', true),
  ('Esomeprazol Granulado para suspensión 2.5mg. Sobres.', true),
  ('Espironolactona tabletas 25 mg', true),
  ('Estreptocinasa Solucion inyectable 750 000 UI/ 5 ml. c/ 5 ml', true),
  ('Estreptomicina Solucion inyectable 1g (c/agua inyectable c/2 ml)', true),
  ('Estrogenos conjugados de origen equino Crema vaginal 0.625mg/g Envase c/43g y aplicador', true),
  ('Estrogenos conjugados de origen equino Grageas o tabletas 0.625 mg', true),
  ('Estrogenos conjugados de origen equino y medroxiprogesterona grageas 0.625mg/2.5mg', true),
  ('Estrogenos conjugados de origen vegetal Grageas o tabletas 0.625 mg', true),
  ('Etomidato Solucion inyectable 20mg/10ml ampolletas c/10ml', true),
  ('Etoposido Solucion inyectable 100 mg ampolletas o frascos ampula c/5ml', true),
  ('Etoricoxib Comprimido 90mg.', true),
  ('Evolocumab 140 mg. Solucion inyectable. PLUMA prellenada con 1 ml.', true),
  ('Ezetimiba 10 mg tabletas', true),
  ('Ezetimiba Tableta 10mg.', true),
  ('Ezetimiba-Simvastatina, comprimido, 10mg/20mg', true),
  ('Factor VIII antihemofilico 500UI, Factor de Von Willdebrand 500UI. Solucion inyectable.', true),
  ('Fenazopiridina Tabletas 100 mg', true),
  ('Fenilefrina Solucion oftalmica 100 mg/ ml Envase con gotero integral c/15ml', true),
  ('Fenitoina (Difenilhidantoina) Susp. oral 37.5 mg/5ml Envase c/120ml y vaso dosificador de 5ml', true),
  ('Fenitoina sodica (difenilhidantoina) tabletas o capsulas 100 mg', true),
  ('Fenitoina sodica Solucion inyectable 250mg/5ml ampolleta con 5 ml', true),
  ('Fenobarbital Tabletas 100 mg', true),
  ('Fentanilo (Fentanil) Solucion inyectable 0.5mg/10ml ampolletas c/10 ml', true),
  ('Fibrinogeno humano solucion inyectable 150g. Fco. amp. c/liofilizado y 100ml diluyente.', true),
  ('Filgrastim Solucion inyectable 300 µg/ml', true),
  ('Finasterida Grageas 5mg', true),
  ('Fitomenadiona Solucion inyectable 10mg/ml Ampolletas c/1ml', true),
  ('Fitomenadiona Solucion inyectable 2mg/ 0.2ml Ampolletas c/0.2ml', true),
  ('Fluconazol Capsulas o tabletas 100mg', true),
  ('Fluconazol Solucion inyectable 2 mg/ ml frasco ampula c/50ml', true),
  ('Fludrocortisona Comprimidos 0.1 mg', true),
  ('Flumazenil Solucion inyectable 0.5mg/5 ml ampolleta c/5ml', true),
  ('Fluocinolona acetonida de Crema 0.1 mg/g Envase con 20 g.', true),
  ('Fluorouracilo Solucion inyectable 250 mg ampolletas c/10ml', true),
  ('Fluoxetina Capsulas o tabletas 20mg', true),
  ('Fluticasona 50µg suspension en aerosol, frasco presurizado para 60 dosis', true),
  ('Fluticasona aerosol nasal 27.5 µg. Frasco con 120 disparos', true),
  ('Fluticasona/vilanterol, polvo para inhalacion 100µg/25µg. Con dispositivo inhalador', true),
  ('Formula de proteinas hidrolizadas sin lactosa Polvo (Prot 12g, lip 17g, carbohid 51g) Env c/400-454g', true),
  ('Fosaprepitan solucion inyectable 150mg. Liofilizado. Envase c/10 frascos ampula.', true),
  ('Fosfato de Oseltamivir 45mg capsulas', true),
  ('Fosfato de potasio S.I. Potasio dibasico 1.550g/10ml, potasio monofasico 0.300g/10ml amp. c/10ml', true),
  ('Fosfolipidos de pulmón porcino 80mg, suspension, envase con 3ml', true),
  ('Fostato de oseltamavir tabletas de 75 mg', true),
  ('Fumarato ferroso Suspension oral 29mg/ml Envase c/120 ml', true),
  ('Furosemida Solucion inyectable 20mg/2ml Ampolletas c/2ml', true),
  ('Furosemida Tabletas 40mg', true),
  ('Gabapentina Capsulas 300mg', true),
  ('Ganciclovir Solucion inyectable 500mg frasco ampula y diluyente c/10ml', true),
  ('Gelatina Solucion inyectable Polimerizado de gelatina succinilada degradada 4g/100ml 500 ml', true),
  ('Gentamicina Solucion inyectable 20mg/2ml Ampolleta con 2ml', true),
  ('Gentamicina Solucion inyectable 80mg/2ml ampolleta c/2ml', true),
  ('Glibenclamida Tabletas 5mg', true),
  ('Glicerina (Glicerol) Supositorio 2.632g', true),
  ('Gluconato de calcio Solucion inyectable al 10% 1g/10ml ampolletas c/10ml', true),
  ('Glucosa Solucion inyectable al 10% Glucosa anhidra 10g/100ml 1000ml', true),
  ('Glucosa Solucion inyectable al 10% Glucosa anhidra 10g/100ml 500ml', true),
  ('Glucosa Solucion inyectable al 5% 5g/100ml 1000ml', true),
  ('Glucosa Solucion inyectable al 5% 5g/100ml 250ml', true),
  ('Glucosa Solucion inyectable al 5% 5g/100ml 500ml', true),
  ('Glucosa Solucion inyectable al 5% 5g/100ml 50ml (con adaptador para vial)', true),
  ('Glucosa Solucion inyectable al 5% 5g/100ml. Envase c/100ml, c/adaptador p/vial.', true),
  ('Glucosa Solucion inyectable al 5% 5g/100ml. Envase c/100ml.', true),
  ('Glucosa Solucion inyectable al 50% 50g/100ml 250ml', true),
  ('Glucosa Solucion inyectable al 50% 50g/100ml 50ml (frasco o bolsa)', true),
  ('Goserelina Implante de liberacion prolongada 3.6mg Env. c/1 implante cilindrico esteril en 1 jeringa', true),
  ('Haloperidol Solucion inyectable 5 mg/ ml 6 ampolletas con un ml', true),
  ('Haloperidol Tabletas 5 mg', true),
  ('Heparina Solucion inyectable 10 000 UI/ 10 ml (1000 UI/ ml) Frascos ampula c/10ml', true),
  ('Heparina Solucion inyectable 1000UI. Envase c/20 Frascos ampula de 1ml.', true),
  ('Heparina Solucion inyectable 25 000 UI/ 5 ml (5000 UI/ ml) Frascos ampula c/5ml', true),
  ('Hidralazina Solucion Inyectable 10mg/ml. Envase c/5 ampolletas.', true),
  ('Hidralazina Solucion inyectable 20 mg Ampolletas c/1ml', true),
  ('Hidralazina Tableta 10 mg', true),
  ('Hidroclorotiazida Tabletas 25 mg', true),
  ('Hidrocortisona (butirato de) Crema 1 mg/g Envase con 15 g', true),
  ('Hidrocortisona S.I. 100mg/ 2ml Frascos ampula y diluyente de 2ml', true),
  ('Hidroxicarbamida (hidroxiurea) Capsulas 500 mg', true),
  ('Hidroxicloroquina 200mg Tabletas.', true),
  ('Hidroxocobalamina Solucion inyectable 100 µg/2ml ampolletas c/2ml', true),
  ('Hierro dextran Solucion inyectable 100 mg/ 2ml ampolletas con 2 ml', true),
  ('Hipromelosa Solucion oftalmica 2% 20 mg/ml Envase con gotero integral 15ml', true),
  ('Hipromelosa Solucion oftalmica al 0.5% 5 mg/ ml Envase con gotero integral con 15ml', true),
  ('Ibrutinib capsulas 420mg', true),
  ('Ibuprofeno capsulas o tabletas de 400 mg', true),
  ('Ibuprofeno suspension oral, 2.0 gr, envase c/120 ml', true),
  ('Idursulfasa solucion inyectable 6mg/3ml', true),
  ('Ifosfamida Solucion inyectable 1g', true),
  ('Imatinib 400mg, comprimidos.', true),
  ('Imipenem y cilastatina Solucion inyectable 500mg/500mg. Frasco ampula.', true),
  ('Imipramina Grageas o tabletas 25 mg', true),
  ('Indacaterol 110µg/Glicopirronio 50µg. Capsula con polvo p/inhalación e inhalador.', true),
  ('Indometacina Capsulas 25 mg', true),
  ('Indometacina Supositorio 100 mg', true),
  ('Infliximab Solucion inyectable 100mg. Liofilizado.', true),
  ('Inmunoglobulina anti D Solucion inyectable 0.300mg/1.5 o 2ml (con o sin diluyente) F.Amp. ó Jeringa', true),
  ('Inmunoglobulina G no modificada. S.I. 6g/200ml fco amp y env. c/200ml de solvente', true),
  ('Insulina aspartica y/o asparta Solucion inyectable 100UI. Pluma c/3ml.', true),
  ('Insulina glargina 3.64 mg/ml. Frasco ampula 10 ml.', true),
  ('Insulina humana accion intermedia NPH Suspension inyectable 100 UI/ml frasco ampula c/10 ml', true),
  ('Insulina humana accion rapida regular Solucion inyectable 100UI/ml frasco ampula c/10 ml', true),
  ('Insulina lispro Solucion inyectable 100 UI/ml. Frasco amp. c/10ml.', true),
  ('Ipratropio 0.50mg/salbutamol 2.mg, ampolleta 2.5ml', true),
  ('Ipratropio solucion 0.25 mg/ml, frasco ampula con 20 ml', true),
  ('Irbesartan 300 mg tabletas', true),
  ('Irbesartan/Amlodipino Tableta Irbesartan 150mg, Besilato de amlodipino equiv. a 10mg de amlodipino.', true),
  ('Irbesartan/hidroclorotiazida 150 mg/12.5mg tabletas', true),
  ('Irinotecan Solucion inyectable 100mg', true),
  ('Isoconazol Crema 1 g/ 100 g Envase con 20 g', true),
  ('Isoflurano Liquido 100 ml Envase con 100 ml', true),
  ('Isosorbida dinitrato de Tabletas 10 mg', true),
  ('Isosorbida dinitrato de Tabletas sublinguales 5 mg', true),
  ('Isosorbida dinitrato de Solucion inyectable 1mg/ml Envase c/100ml', true),
  ('Itraconazol Capsulas 100 mg', true),
  ('Ivermectina tabletas 6mg', true),
  ('Ketamina Solucion inyectable 500mg/10ml, frasco ampula c/10ml', true),
  ('Ketoconazol Tabletas 200 mg', true),
  ('Ketorolaco trometamina Solucion Inyectable 30mg Ampolletas 1 ml', true),
  ('Labetalol Solucion inyectable 100mg/20ml.', true),
  ('Lacosamida 200mg/20ml solucion inyectable', true),
  ('Lacosamida tabletas 100 mg', true),
  ('Lactulosa 66.7gr/100ml. Jarabe. Envase c/120ml', true),
  ('Lactulosa 66.7gr/100ml. Jarabe. Envase c/240 ml', true),
  ('Lamotrigina Tabletas 100mg.', true),
  ('Lenalidomida 10mg, cápsulas.', true),
  ('Lenalidomida 15mg, cápsulas.', true),
  ('Lenalidomida 25mg, cápsulas.', true),
  ('Leuprorelina 22.5mg Suspension inyectable', true),
  ('Levetiracetam solucion oral 100 mg/ml, envase c/300ml', true),
  ('Levetiracetam tabletas de 500 mg', true),
  ('Levocetirizina Tabletas 5mg.', true),
  ('Levodopa y carbidopa Tabletas 250 mg/ 25 mg', true),
  ('Levofloxacino solucion inyectable 500 mg/100ml Envase 100ml', true),
  ('Levofloxacino tabletas 500 mg', true),
  ('Levofloxacino tabletas 750 mg', true),
  ('Levosimendan 2.5mg/ml solucion inyectable', true),
  ('Levotiroxina (Levotiroxina sodica) Tabletas 100µg', true),
  ('Levotiroxina (Levotiroxina sodica) Tabletas 25µg', true),
  ('Lidocaina con hidrocortisona Supositorio 60 mg/5 mg', true),
  ('Lidocaina con hidrocortisona Ungüento 50 mg/1 g y 2.5 mg/1 g Envase c/20g y aplicador', true),
  ('Lidocaina Parche adhesivo 700mg. Sobre c/5 parches.', true),
  ('Lidocaina Solucion al 10% 10g/100ml, frasco 115ml c/atomizador manual', true),
  ('Lidocaina Solucion inyectable al 1% 500 mg/50ml, frasco ampula c/50ml', true),
  ('Lidocaina Solucion inyectable al 2% 1g/50ml, frasco ampula c/50ml', true),
  ('Lidocaina y Epinefrina S.I. al 2% cartuchos dentales c/1.8 ml', true),
  ('Lidocaina y Epinefrina S.I. al 2%, (20mg/0.005mg) fcos ampula c/50ml', true),
  ('Linagliptina 5mg tabletas', true),
  ('Linezolid inyectable 200mg/300ml. Bolsa de 300ml.', true),
  ('Linezolid tabletas de 600mg', true),
  ('Lipidos intravenosos Emulsion iny. a 20% Lipidos intravenosos de cadena med. y larga Env c/500ml', true),
  ('Liraglutida solucion inyectable de 6 mg/ml, caja con 2 jeringas precargadas', true),
  ('Litio, carbonato de, Tabletas 300 mg', true),
  ('Loperamida Tabletas o grageas 2 mg', true),
  ('Loratadina Jarabe 5 mg/5 ml Envase con 60 ml', true),
  ('Loratadina Tabletas o grageas 10 mg', true),
  ('Lorazepam Tabletas 1 mg', true),
  ('L-Ornitina L-Aspartato granulado 3g', true),
  ('L-ornitina-l-aspartato 5gr. Solucion inyectable. Ampolletas de 10ml.', true),
  ('Losartan potasico Grageas 50 mg', true),
  ('Magnesio sulfato de Solucion inyectable 1g/10ml ampolletas c/10ml', true),
  ('Manitol Solucion inyectable al 20% 50g/250ml Envase c/250 ml', true),
  ('Medroxiprogesterona Comprimidos 10 mg', true),
  ('Meloxicam Tabletas 15 mg', true),
  ('Mercaptopurina Tabletas 50 mg', true),
  ('Meropenem Solucion inyectable 1g', true),
  ('Mesalazina 1gr. Supositorios.', true),
  ('Mesalazina 6.667gr/100ml. Susp. rectal. Enema de 60ml.', true),
  ('Mesalazina Grageas con capa enterica 500 mg', true),
  ('Mesilato de Imatinib, comprimido recubierto, 100 mg.', true),
  ('Mesna Solucion inyectable 400mg/4ml ampolletas c/4ml', true),
  ('Metadona 10 mg solucion oral, envase c/30 ml', true),
  ('Metamizol sodico (Dipirona) Comprimidos 500 mg', true),
  ('Metamizol sodico (Dipirona) Solucion inyectable 1g/2ml ampolletas c/2ml', true),
  ('Metformina Tabletas 850 mg', true),
  ('Metildopa (l-alfametildopa) Tabletas 250 mg', true),
  ('Metilfenidato Comprimidos 10mg', true),
  ('Metilfenidato, tabletas de liberacion prolongada 18mg', true),
  ('Metilfenidato. Tableta de Liberación Prolongada 27 mg', true),
  ('Metilprednisolona Solucion inyectable 500mg/8ml Ampolletas de 8ml', true),
  ('Metilprednisolona Suspension inyectable 40 mg/ ml frasco ampula c/2ml', true),
  ('Metoclopramida Solucion inyectable 10mg/2ml ampolletas c/2ml', true),
  ('Metoclopramida Solucion oral 4 mg/ml Envase con 20 ml c/gotero integrado', true),
  ('Metoclopramida Tabletas 10 mg', true),
  ('Metoprolol Tabletas 100 mg', true),
  ('Metotrexato Solucion inyectable 500 mg / 20 ml', true),
  ('Metotrexato Solucion inyectable 50 mg / 2 ml', true),
  ('Metotrexato Tabletas 2.5 mg', true),
  ('Metronidazol ovulos o tabletas vaginales 500 mg', true),
  ('Metronidazol Solucion inyectable 200mg/10ml ampolletas c/10ml', true),
  ('Metronidazol Solucion inyectable 500mg/100ml frasco ampula o bolsa c/100ml', true),
  ('Metronidazol Suspension oral 250 mg/ 5 ml Envase con 120 ml', true),
  ('Metronidazol Tabletas 500 mg', true),
  ('Midazolam Solucion inyectable 15mg/3ml. Ampolletas c/3ml', true),
  ('Midazolam Solucion inyectable 50 mg ampolletas c/10ml', true),
  ('Midazolam Solucion inyectable 5mg/5ml. Ampolletas c/5ml', true),
  ('Mifepristona 200mg. Tabletas. Envase c/1 tab.', true),
  ('Mifepristona 200mg. Tabletas. Envase c/3 tabs.', true),
  ('Milrinona 10mg/10ml solucion inyectable, Fco. Ampula c/10ml', true),
  ('Mirtazapina tabletas 30 mg', true),
  ('Mitoxantrona Solucion inyectable 20mg/10ml', true),
  ('Mometasona suspension p/inhalacion, 0.050g. Envase c/18ml. (140 nebulizaciones de 50µg c/u)', true),
  ('Montelukast 5 mg tableta masticable', true),
  ('Morfina pentahidratada 2.5mg. Solucion inyectable. Ampolletas de 2.5ml', true),
  ('Morfina pentahidratada 50mg. Solucion inyectable. Ampolleta de 2.0ml', true),
  ('Morfina Solucion inyectable 10 mg/ml', true),
  ('Morfina Tabletas 30 mg', true),
  ('Multivitaminas S. I. (infantil) Vitaminas fco ampula y diluyentes c/5ml', true),
  ('Multivitaminas Solucion inyectable (adulto) Vitaminas (diluyente c/5ml)', true),
  ('Mupirocina Ungüento 2 g/100 g Envase con 15 g', true),
  ('Nafazolina Solucion oftalmica 1 mg/ml Envase con gotero integral con 15 ml', true),
  ('Nalbufina Solucion inyectable 10 mg/ml', true),
  ('Naloxona Solucion inyectable 0.4 mg/ ml ampolletas c/1ml', true),
  ('Naproxeno Tabletas 250 mg', true),
  ('Neomicina, polimixina B y acetonida de fluocinolona Sol. otica Envase c/gotero integral c/5ml', true),
  ('Neomicina, polimixina B y bacitracina Ungüento oftalmico Envase con 3.5 g', true),
  ('Neostigmina Solucion inyectable 0.5 mg/ ml ampolletas c/1ml', true),
  ('Nifedipino Capsulas de gelatina blanda 10 mg', true),
  ('Nifedipino Comprimido de liberación prolongada 30 mg', true),
  ('Nimodipino S.I. 10 mg/50ml Fco. amp. c/50ml y eqpo perfusor de polietileno', true),
  ('Nistatina ovulos o tabletas vaginales 100 000 UI', true),
  ('Nistatina suspesion oral 2 400 000 UI envase para 24ml', true),
  ('Nitrato de Miconazol crema 20 mg/1g (2%) envase c/20 g', true),
  ('Nitrofurantoina Capsulas 100 mg', true),
  ('Nitrofurantoina Suspension oral 25 mg/ 5ml Envase con 120 ml', true),
  ('Nitrofurazona ovulos 6mg', true),
  ('Nitroprusiato de sodio Solucion inyectable 50 mg/ 2 ml frasco ampula c/2ml', true),
  ('Norepinefrina (noradrenalina) Solucion inyectable 4 mg/4ml', true),
  ('Obinutuzumab solución inyectable 1000mg envase con 40 ml', true),
  ('Octreotida Solucion inyectable 1mg frasco ampula c/5ml', true),
  ('Octreotida suspension inyectable 20mg. Fco. ampula y dos diluyentes', true),
  ('Olanzapina Sol. Iny. 10 mg', true),
  ('Olanzapina Tabletas 10 mg', true),
  ('Oligometales endovenosos (Zi, Cu, Ma, So, Y, F, Cl). Solucion inyectable. Frascos ampula c/20ml', true),
  ('Omeprazol Solucion inyectable 40 mg Frasco ampula o Ampolleta c/10ml', true),
  ('Ondansetron Solucion inyectable 8mg/4ml', true),
  ('Ondansetron tabletas 8 mg', true),
  ('Orciprenalina Solucion inyectable. 0.5mg/ml ampolletas c/1ml', true),
  ('Oxcarbazepina Gragea o tableta 300mg.', true),
  ('Oxcarbazepina suspension oral 6gr. 6gr/100ml. Envase c/100ml.', true),
  ('Oxido de zinc (Lassar) Pasta 25 g/100 g Envase con 30 g', true),
  ('Oxitocina. Solucion inyectable. 5 UI/ ml ampolletas c/1ml', true),
  ('Palivizumab 100mg. Solucion inyectable. Frasco ampula con 0.5ml.', true),
  ('Palonosetron 0.25mg/5l solucion inyectable, envase c/5 ml', true),
  ('Pantopazol 40mg o Rabeprazol 20mg u Omeprazol 20mg. Tabletas o Capsulas.', true),
  ('Paracetamol (Acetaminofen) Solucion oral 100 mg/ml Envase con gotero 15 ml', true),
  ('Paracetamol (Acetaminofen) Supositorios 100 mg', true),
  ('Paracetamol (Acetaminofen) Supositorios 300 mg', true),
  ('Paracetamol (Acetaminofen) Tabletas 500 mg', true),
  ('Paracetamol sol. inyectable 1gr/100ml. Env. c/10 Frascos ampula', true),
  ('Paroxetina Tabletas 20 mg', true),
  ('Pegaspargasa 3750UI/5mL solucion inyectable', true),
  ('Pegfilgrastim 6mg/0.6ml, jeringa prellenada', true),
  ('Pentoxifilina Tabletas o grageas de liberacion prolongada 400mg', true),
  ('Perindopril/Amlodipino Comprimidos, Perindopril Arginina 10mg, Amlodipino 5mg.', true),
  ('Perindopril/Amlodipino/Indapamida comprimidos 5mg/5mg/1.25mg', true),
  ('Perindopril/Indapamida comprimidos 5mg/1.25mg', true),
  ('Permetrina Shampoo Solucion al 1%', true),
  ('Pilocarpina Solucion oftalmica al 2% 20 mg/ ml Envase c/gotero integral c/15ml', true),
  ('Pinaverio 100mg. Tabletas. Env. c/28 tabs.', true),
  ('Pioglitazona 15 mg tabletas', true),
  ('Piperacilina / Tazobactam 4g/500mg, Fco. Ampula c/polvo, sin diluyente', true),
  ('Pirfenidona 600 mg tabletas', true),
  ('Plantago psyllium Polvo 49.7 g Envase con 400 g', true),
  ('Podofilino Solucion dermica. 250 mg/ml. Envase con 5 ml', true),
  ('Polidocanol Solucion inyectable 30mg/ml frasco ampula c/30ml', true),
  ('Polietilenglicol 105g polvo (sobres)', true),
  ('Poligelina Solucion inyectable 3.5g/100ml 500ml', true),
  ('Polivitaminas y Minerales Jarabe Vitaminas y minerales Envase con 240 ml', true),
  ('Polivitaminas y minerales tabletas, grageas o capsulas', true),
  ('Pramipexol tableta 0.5mg', true),
  ('Pramipexol tabletas 1mg', true),
  ('Pravastatina Tabletas 10 mg', true),
  ('Prazosina Capsulas o comprimidos 1 mg', true),
  ('Prednisolona Solucion oftalmica 5mg/ml Envase con gotero integral con 5 ml.', true),
  ('Prednisolona, solucion oral 100mg/100ml, envase c/100ml', true),
  ('Prednisona tabletas 20 mg', true),
  ('Prednisona Tabletas 5 mg', true),
  ('Prednisona Tabletas 50 mg', true),
  ('Pregabalina 75 mg capsulas', true),
  ('Progesterona gel. Concentracion 1gr/100gr. Con regla dosificadora', true),
  ('Propofol Emulsion inyectable 200 mg/20 ml ampolletas o frascos ampula c/20ml', true),
  ('Propofol Emulsion inyectable 500 mg/50 ml Frasco ampula de 50 ml', true),
  ('Propranolol Tabletas 40 mg', true),
  ('Protamina Solucion inyectable 71.5mg/ 5ml ampolleta c/5ml', true),
  ('Quetiapina tabletas 100 mg', true),
  ('Racecadotrilo granulado oral 30mg', true),
  ('Raloxifeno tabletas 60 mg', true),
  ('Resina de colestiramina polvo 4g, sobre', true),
  ('Rifaximina 200mg. Tabletas.', true),
  ('Rifaximina 550 mg. Tabletas', true),
  ('Risperidona 25 mg. Envase con frasco ampula y jeringa prellenada con 2 ml de diluyente', true),
  ('Risperidona Tabletas 2 mg', true),
  ('Risperidona, solucion oral, 1mg/ml, envase c/60 ml', true),
  ('Rituximab 100mg/10ml solucion inyectable, envase c/2 fcos ampulas de 10 ml', true),
  ('Rituximab Solucion inyectable 500 mg. Fco. ampula de c/50 ml.', true),
  ('Rituximab Solucion inyectable 500mg Envase c/50ml con dos frasco ampula', true),
  ('Rivaroxaban 10mg. Comprimidos.', true),
  ('Rivaroxaban camprimido 2.5mg.', true),
  ('Rivaroxavan comprimidos 15mg.', true),
  ('r-L-Asparginasa Solucion inyectable 10,000 UI Liofilizado', true),
  ('Rocuronio Solucion inyectable 50 mg/5 ml', true),
  ('Romiplostim 375µg ampula; 250µg/0.5ml', true),
  ('Ropivacaina 150mg/20ml ampolletas de 20 ml', true),
  ('Rosuvastatina tabletas 10mg', true),
  ('Ruxolitinib tableta 20 mg', true),
  ('Ruxolitinib tabletas 10mg.', true),
  ('Sacubitrilo valsartan comprimidos 50mg.', true),
  ('Salbutamol Jarabe 2 mg/ 5 ml Envase con 60 ml', true),
  ('Salbutamol Solucion para respiradores(nebulizadores) 0.5g/100 ml Envase c/10ml', true),
  ('Salbutamol suspension aerosol 20mg envase c/inhalador c/200 dosis de 100 µg', true),
  ('Sales de potasio tabletas solubles, Bicarbonato de potasio 766mg, Bitartrato de potasio 460 mg...', true),
  ('Secukinumab Solucion inyectable 150g. Env. c/2 plumas precargadas con 1ml.', true),
  ('Semaglutida Tabletas 3mg. GLP-1 de origen ADN recombinante.', true),
  ('Semaglutida Tabletas 7mg GLP-1 de origen ADN recombinante', true),
  ('Senosidos A-B Tabletas 8.6mg', true),
  ('Seroalbumina humana Solucion inyectable 12.5g/50ml 50 ml', true),
  ('Sertralina Capsulas 50 mg', true),
  ('Sevelamero tabletas 800mg,', true),
  ('Sevoflurano Liquido 250 ml Envase con 250 ml', true),
  ('Sildenafil tabletas 50 mg', true),
  ('Simoctocog alfa Solucion inyectable 250UI. Frasco ampula c/250UI. Env. c/Liofilizado, jeringa ...', true),
  ('Simoctocog alfa, sol. iny. 1000 UI, frasco ampula con polvo liofilizado', true),
  ('Simoctocog alfa, sol. iny. 500UI, frasco ampula con polvo liofilizado', true),
  ('Sitagliptina 50mg (Fosfato). Comprimidos', true),
  ('Sitagliptina comprimidos 100 mg', true),
  ('Sitagliptina con metformina. Comprimidos 50mg/850mg', true),
  ('Sodio fosfato y citrato de Sol. p/enema 12g/100ml 10g/100ml Env. c/133 ml y canula rectal', true),
  ('Solucion Hartmann 1000 ml', true),
  ('Solucion Hartmann 500 ml', true),
  ('Solucion p/dialisis peritoneal al 1.5% baja en magnesio, envase c/bolsa de 2 ltr y bolsa drenaje', true),
  ('Solucion p/dialisis peritoneal al 2.5% baja en magnesio, envase c/bolsa de 2 ltr y bolsa drenaje', true),
  ('Solucion p/dialisis peritoneal al 4.25% baja en magnesio, envase c/bolsa de 2 ltr y bolsa drenaje', true),
  ('Somatropina Solucion inyectable 4 UI Frasco ampula y ampolleta c/1 o 2ml de diluyente', true),
  ('Sucedaneo de leche humana de pretermino polvo P:15g, L:29g, C:57g Env. c/400 a 454g', true),
  ('Sucralfato Tabletas 1g', true),
  ('Sulfadiazina de plata micronizada Crema 1g/100g. Envase con 375 g', true),
  ('Sulfasalazina Tableta con capa enterica 500mg', true),
  ('Sulfato ferroso Solucion oral 125 mg/ ml Envase gotero c/15ml', true),
  ('Sulfato ferroso Tabletas 200 mg', true),
  ('Tamsulosina Capsula de Liberacion Prolongada 0.4 mg', true),
  ('Telmisartan 40 mg Tabletas', true),
  ('Telmisartan 80mg / Hidroclorotiazida 12.5 mg tabletas', true),
  ('Tenecteplasa sol. iny. 50mg (10,000 U), Fco. Amp y Jeringa Prellenada c/10 ml de agua inyectable', true),
  ('Terlipresina Solucion inyectable 1mg, Fraco amp. c/liofilizado y diluyente.', true),
  ('Tetracaina Solucion oftalmica 5 mg/ ml Envase con gotero integral c/10ml', true),
  ('Tiamazol Tabletas 5 mg', true),
  ('Tiamina Solucion inyectable 500 mg', true),
  ('Tibolona Tabletas 2.5 mg', true),
  ('Tigeciclina Solucion inyectable 50mg.', true),
  ('Timolol Solucion oftalmica 5mg/ml Envase c/gotero integral c/5ml', true),
  ('Tiopental sodico Solucion inyectable 0.5g/20ml, frasco ampula y diluyente c/20ml', true),
  ('Tobramicina 300mg/5ml. Solucion p/nebulizar. Env c/14 sobres de 4 amp c/u.', true),
  ('Tobramicina Solucion oftalmica 3mg/ml Envase con gotero integral c/15 ml', true),
  ('Tobramicina Solucion oftalmica 3mg/ml Envase con gotero integral c/5ml', true),
  ('Tolterodina Tabletas 2 mg', true),
  ('Topiramato Tabletas 100 mg', true),
  ('Topiramato Tabletas 25 mg', true),
  ('Toxina botulinica tipo A Solucion inyectable 100UI. Complejo purificado neutotoxina', true),
  ('Tramadol Solucion inyectable 100mg/ 2ml', true),
  ('Tramadol Tabletas de liberacion prolongada 150mg.', true),
  ('Tretinoina Capsulas 10 mg', true),
  ('Trifluoperazina Grageas 5 mg', true),
  ('Trihexifenidilo Tabletas 5 mg', true),
  ('Trimetoprima y sulfametoxazol Solucion inyectable 800mg 160mg ampolletas c/3ml', true),
  ('Trimetoprima y sulfametoxazol Suspension oral 40mg/200mg/5ml Envase con 120 ml', true),
  ('Trimetoprima y sulfametoxazol Tabletas 80mg/400mg', true),
  ('Trinitrato de glicerilo Parche 5mg/dia', true),
  ('Trinitrato de glicerilo Solucion inyectable 50mg/10ml Envase c/10ml', true),
  ('Tropicamida Solucion oftalmica 1 g/100 ml Envase con gotero integral c/5ml', true),
  ('Valproato de magnesio 200mg (185.6mg ácido valproico) Tabletas con cubierta enterica', true),
  ('Valproato de magnesio Solucion oral 186 mg/ ml Envase con 40 ml', true),
  ('Valproato de magnesio, tabletas de liberacion prolongada 600 mg', true),
  ('Valproato semisodico (acido valproico) 250mg, comprimido c/capa enterica', true),
  ('Vancomicina Solucion inyectable 500 mg', true),
  ('Vasopresina Solucion inyectable 20 UI', true),
  ('Vecuronio Solucion inyectable 4mg/ml ampolletas o frascos ampula c/1ml', true),
  ('Venetoclax 100 mg. Tabletas.', true),
  ('Venlafaxina 75mg capsulas o gragea de liberacion prolongada', true),
  ('Verapamilo Gragea o Tableta recubierta 80 mg', true),
  ('Verapamilo Solucion inyectable 5mg/2ml ampolleta c/2ml', true),
  ('Vinblastina Solucion inyectable 10 mg. Incluye ampolleta con 10ml de diluyente.', true),
  ('Vincristina Solucion inyectable 1mg/10ml (diluyente c/10 ml)', true),
  ('Vitaminas A, C y D Solucion oral Envase con 15 ml.', true),
  ('Vitaminas y minerales solucion oral envase c/60 ml', true),
  ('Voriconazol Solucion inyectable 200mg.', true),
  ('Voriconazol tabletas de 200mg', true),
  ('Warfarina Tabletas 5 mg', true),
  ('Zuclopentixol Solucion inyectable 200 mg', true)
ON CONFLICT (nombre) DO UPDATE SET activo = true;

-- 3) POST-CHECK: conteos por estado
SELECT
  count(*) FILTER (WHERE activo) AS activos_total,
  count(*) FILTER (WHERE activo AND grupo_control IS NULL) AS activos_generales,
  count(*) FILTER (WHERE activo AND grupo_control IS NOT NULL) AS activos_controlados,
  count(*) FILTER (WHERE NOT activo) AS inactivos
FROM catalogo_medicamentos;

COMMIT;
